### ISSUE TITLE
Sharper not installation error caused by node-gyp

### ISSUE THREAD

**Issue by iyunusov** [nodejs/node-gyp#1081] opened 2016-12-28 14:30 UTC
```
npm install -g sharper

> sharp@0.15.1 install /home/peace/npm/lib/node_modules/sharper/node_modules/sharp
> node-gyp rebuild

ERROR: Intel Architecture 32-bit systems require manual installation - please see http://sharp.dimens.io/en/stable/install/
gyp: Call to 'LDD_VERSION="ldd (Ubuntu GLIBC 2.21-0ubuntu4) 2.21
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper." node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-77-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/peace/npm/lib/node_modules/sharper/node_modules/sharp
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
/home/peace/npm/lib
└── (empty)

npm ERR! Linux 3.19.0-77-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "sharper"
npm ERR! node v5.4.0
npm ERR! npm  v3.7.0
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.15.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.15.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peace/npm-debug.log
npm ERR! code 1
```

**Comment by bnoordhuis** [comment] 2017-01-10 12:29
> ERROR: Intel Architecture 32-bit systems require manual installation - please see http://sharp.dimens.io/en/stable/install/

So no, not caused by node-gyp.  Closing.

**Closed by bnoordhuis** 2017-01-10 12:29 UTC
