### ISSUE TITLE
 binding.gyp not found (cwd: c:\Users\xxxx\xxxx\) while trying to load binding.gyp

### ISSUE THREAD

**Issue by gonadn** [nodejs/node-gyp#702] opened 2015-08-24 14:49 UTC
Hi 

Iam having trouble to configure "node-gyp",
I followed this article "https://github.com/nodejs/node-gyp" for installation of "node-gyp", and it was working before i messed up my configuration on my computer,  node-gyp just stop working. By searching on google i found different explanations, but nothing fixed my issue.

Below is screenshot of when i Run the command "node-gyp configure"
I hope that the path to root directory is correct?

![node](https://cloud.githubusercontent.com/assets/3224441/9443075/6260e6fa-4a7f-11e5-80a8-63dcd6bfea1d.PNG)

By searching on google i found out that if i put an empety binding.gyp file in folder where iam running the command to configure node-gyp , then something start happening, but then i get another error to . So something is maybe missing here or i have done something i cant figure out...

I have installed VS2012 Express and VS2015 PRO, i also have run the npm command to set python and npm to --msvs_version=auto

Any clue on how to configure node-gyp on windows 8.1?

**Comment by bnoordhuis** [comment] 2015-08-24 14:59
What exactly are you trying to do?  node-gyp is for building add-ons.  From your screenshot, it looks like you're trying to build node-gyp itself.

**Comment by gonadn** [comment] 2015-08-24 15:03
hmmm...oki, iam trying to install bcrypt, when i first tried to install bcrypt i got an error saying that i need to run node-gyp rebuild, and thats where all started...

I need to install bcrypt...

**Comment by gonadn** [comment] 2015-08-24 15:16
bnoordhuis , Where shoud i run this command from? in witch directory?  

In installation describtions they say that you need to run the command from the root directory of you node.....what does it mean?

**Comment by bnoordhuis** [comment] 2015-08-24 19:19
node-gyp is installed along with npm, there should be no need to install it separately.  If you get an error when you `npm install bcrypt`, you should take that up with the bcrypt project first.

**Comment by gonadn** [comment] 2015-08-25 21:24
I no that, problom is when i try to install bcrypt i get an error saying that i have to run "node-gyp configure" before installing the bcrypt. And when i run node-gyp configure, i get another error saying that node-gyp can not find the binding.gyp file......!! And i cant find any binding.gyp file in the root of directory....

**Comment by TooTallNate** [comment] 2015-08-25 22:18
You should not need to run `node-gyp configure` manually. This happens implicitly when `npm install bcrypt` is run.

Closing since not a node-gyp issue.

**Closed by TooTallNate** 2015-08-25 22:18 UTC
Labels: Windows

**Comment by gonadn** [comment] 2015-08-26 06:14
Shut the fuck up,

How can you say that this is not a node-gap issue? 
This node-gap shitt is not working and i have to configure node-gap before i can install bcrypt. So before taking any disicion on weather it is node-gap issue or not, try to help to solve the issue, this is related to FUCKEN node-gap....

**Comment by gonadn** [comment] 2015-08-26 07:54
the solution in my case was to run this command:

set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

**Comment by shraddha22** [comment] 2016-01-14 06:54
I am getting the same issue. I tried a lot but couldnt fix this issue. Setting Path with MSBuild is also not working for e. I am getting this issue when I am trying to install ursa module. Also, i am using VS2012 Express.Please help
![npm install](https://cloud.githubusercontent.com/assets/14349786/12317714/ba64c54c-bab9-11e5-9fc0-b96affdf5c3c.PNG)

**Comment by kala725** [comment] 2016-05-30 12:28
Try running the following commands and then run npm install 

sudo npm cache clean -f
sudo npm install -g n
sudo n 4.4.5
sudo npm install npm -g
sudo npm uninstall node-gyp -g
sudo npm uninstall node-gyp

**Comment by waltdakind** [comment] 2016-07-26 03:36
I am running into the same problem, the sudo commands are not applicable to a windows environment (and the npm package 'n' is not either).  I get the same binding.gyp, and that's after successfully reinstalling node-gyp using the msvs_version.  Elsewhere I've seen suggestions to reinstall Python. Anyone have other ideas?

**Comment by Steviey** [comment] 2016-10-09 12:47
+1

**Comment by wzup** [comment] 2016-11-16 19:48
+1

**Comment by h4ck4life** [comment] 2017-01-18 08:57
+1

**Comment by lber19535** [comment] 2017-01-18 09:17
Just use VS developer command prompt if you have VS

**Comment by maloca1992** [comment] 2017-01-21 18:25
+1

**Comment by tewest** [comment] 2017-02-16 04:34
+1

**Comment by Steviey** [comment] 2017-02-16 04:49
I fixed it somehow after two weeks or so. It was a hell of trial and error. 
The process was so complex, that at the end I wasn't sure what fixed it.
Gyp is an illness. Good luck!

**Comment by a3zzat** [comment] 2017-03-28 20:00
the same issue and no solution

**Comment by himadrinath** [comment] 2017-04-15 13:55
**MOAE** Mother of All Error. 

no clear solution more then 72 hours already spend just to fixed it.

**Comment by adamwallace** [comment] 2017-04-28 21:19
I feel pretty silly, but I realized that I didn't have Visual C++ 2015 Build Tools and Visual Studio with Common Build tools (or relevant C++ addons). I installed both of those and didn't have this problem anymore.

**Comment by SaiMounikaRao** [comment] 2017-05-11 16:02
mounika$ node-gyp configure --msvs_version=2015
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@7.4.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mounika/FULLClient-Electron-aw-lily/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mounika/.node-gyp/7.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/mounika/.node-gyp/7.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/mounika/FULLClient-Electron-aw-lily',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/mounika/FULLClient-Electron-aw-lily) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "--msvs_version=2015"
gyp ERR! cwd /Users/mounika/FULLClient-Electron-aw-lily
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 


Can anyone help me to solve this error?

**Comment by gibfahn** [comment] 2017-05-11 16:15
@SaiMounikaRao is there a `binding.gyp` file in your working directory (`/Users/mounika/FULLClient-Electron-aw-lily`)?

Also it looks like you're using a Mac, but `--msvs_version=2015` is a Windows specific option.

**Comment by SaiMounikaRao** [comment] 2017-05-12 06:24
No binding.gyp is not present in my directory.

**Comment by gibfahn** [comment] 2017-05-12 09:12
@SaiMounikaRao so what exactly are you trying to do? You should just be able to do `npm install` in `/Users/mounika/FULLClient-Electron-aw-lily`, I'm not sure why you're running node-gyp directly.

**Comment by SaiMounikaRao** [comment] 2017-05-12 11:08
Ya I got it now it's working fine.

**Comment by mailparikshit** [comment] 2017-05-17 07:05
how did you resolved your problem??

**Comment by refack** [comment] 2017-05-17 12:42
Suggested solutions that came up in this thread:
1. Make sure you have a compiler set up - https://github.com/nodejs/node-gyp/#installation
2. Make sure you have the latest `npm` - https://docs.npmjs.com/getting-started/installing-node
3. sometimes `node-gyp` does not need to be run directly, just `npm i` will trigger it https://github.com/nodejs/node-gyp/issues/702#issuecomment-301026128

@mailparikshit what exactly is the problem you are seeing? You could open a new issue with the error out you got?

**Comment by jeanru** [comment] 2017-09-08 02:57
I create binding.gyp file manually under the path c:\users\leon\appdata\roaming\npm\node_modules\node-gyp with following content:
{
  "targets": [
    {
      "target_name": "binding",
      "sources": [ "build/Release/binding.node" ]
    }
  ]
}. 
After that, I run node-gyp rebuild command and the issue is solved.

**Comment by odahcam** [comment] 2017-12-15 19:48
I think we just shouldn't try to `node-gyp rebuild`, because, in most of cases, it will not solve any other issues.

**Comment by btoo** [comment] 2017-12-30 07:36
im using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) and i was able to fix my problem by doing `sudo apt-get install g++`

**Comment by mounir-m** [comment] 2018-07-02 07:19
I've been running for the same issue for the past few days, here what you need to do : 
  - Install python 2.x.x
  - run npm install --global --production windows-build-tools
  - And most important part : don't forget to add **The "binding.gyp" file** in your project folder:   
     check here https://github.com/nodejs/node-gyp#the-bindinggyp-file

   I guess most people (it was my case) forget to simply add binding.gyp 

Hope it helps ...

**Comment by divgit** [comment] 2019-02-28 10:10
My solution on Windows 10. 
Only these solution helps.
You need file **visualcppbuildtools_full.exe** !!
Go here https://visualstudio.microsoft.com/ru/visual-cpp-build-tools/
My link: https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe
You require file: visualcppbuildtools_full.exe.
Install all versions for windows 8.1 and 10 (~6-8Gb).
Its create folder C:\Program Files (x86)\MSBuild\**Microsoft.Cpp\v4.0\v140...**
And be happy :-)

**Comment by giegiey** [comment] 2019-05-04 02:33
> I create binding.gyp file manually under the path c:\users\leon\appdata\roaming\npm\node_modules\node-gyp with following content:
> {
> "targets": [
> {
> "target_name": "binding",
> "sources": [ "build/Release/binding.node" ]
> }
> ]
> }.
> After that, I run node-gyp rebuild command and the issue is solved.

Best answer .

**Comment by Tenodec** [comment] 2019-06-03 12:32
> I create binding.gyp file manually under the path c:\users\leon\appdata\roaming\npm\node_modules\node-gyp with following content:
> {
> "targets": [
> {
> "target_name": "binding",
> "sources": [ "build/Release/binding.node" ]
> }
> ]
> }.
> After that, I run node-gyp rebuild command and the issue is solved.

good！！！！！！！1

**Comment by shanemac10** [comment] 2019-08-21 19:22
> I create binding.gyp file manually under the path c:\users\leon\appdata\roaming\npm\node_modules\node-gyp with following content:
> {
> "targets": [
> {
> "target_name": "binding",
> "sources": [ "build/Release/binding.node" ]
> }
> ]
> }.
> After that, I run node-gyp rebuild command and the issue is solved.

This worked for me!
Here is a more detailed answer...

If you run `node-gyp rebuild`, or in my dumb case `sudo node-gyp rebuild -g --unsafe-perm=true`, you will probably be looking at a bunch of these logs... `gyp ERR! ...`.

Right in-between the `gyp info` and the `gyp ERR!` look for something like this...
`gyp: binding.gyp not found (cwd: /Users/yourUsername/Documents/YourProject/YourSubFolder) while trying to load binding.gyp`

This is the folder where you need to add a binding.gyp file that contains...

```
{
	"targets": [
		{
			"target_name": "binding",
			"sources": [ "build/Release/binding.node" ]
		}
	]
}
```

Then try running `node-gyp rebuild` again! Good luck all!

**Comment by LincolnTx** [comment] 2019-11-01 16:17
> Try running the following commands and then run npm install, this will take the node's default node-gyp module. (No need to have multiple as node package already provides that)
> 
> **Updating the node & NPM**
> 
> sudo npm cache clean -f
> sudo npm install -g n
> sudo n 4.4.5
> sudo npm install npm -g
> 
> **Removing additional Node-gyp module**
> 
> sudo npm uninstall node-gyp -g
> sudo npm uninstall node-gyp

This solve my issue, thanks man

**Comment by YUPENG12138** [comment] 2019-11-06 08:23
You need to create it
https://github.com/nodejs/node-gyp#the-bindinggyp-file

**Comment by pauljfx** [comment] 2019-11-14 05:29
If you, like me, found this page and do not understand what all these people are talking about but having the same problem (error message when trying to install `yarn/npm install`) maybe we are in the same boat.

I understand that it is a little off-topic, but I hope it helps someone:

So I got this error trying to install something with dependency on `node-sass`.
The node-sass dependency has older version and apparently does not support the latest `node` version I have on my computer.
So to solve this I could either upgrade `node-sass` or downgrade node.

Cheers.

**Comment by dukeatcoding** [comment] 2019-11-22 11:21
@pauljfx to which version of node did you downgrade - is 11 fine or do you need to go back further?

**Comment by B4Lee** [comment] 2020-01-07 16:26
I just solved the problem by reading this article

> https://spin.atomicobject.com/2019/03/27/node-gyp-windows/

hope it helps !!

**Comment by min9nim** [comment] 2020-01-28 22:07
Maybe this helps you if you are on MacOS catalina (v.10.15.XX). 

https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md

**Comment by konstantinkrassmann** [comment] 2020-02-23 09:09
> node-sass

This brought me here. I updated my nodejs to 12 and apparently i didnt check node-sass for compatibility setting it's version to 4.13.1 fixed the whole thing. (remove node_models and package-lock.json afterwards and npm i )

**Comment by skashfykv** [comment] 2020-03-23 18:43
> oki, iam trying to install bcrypt, when i first tried to install bcrypt i got an error saying that i need to run node-gyp rebuild, and thats where all started... I need to install Bcrypt...
> 
> And i have done all the installation steps described:
> 
> I need to install bcrypt...

**Comment by Maelfyn** [comment] 2020-03-31 16:52
> I create binding.gyp file manually under the path c:\users\leon\appdata\roaming\npm\node_modules\node-gyp with following content:
> {
> "targets": [
> {
> "target_name": "binding",
> "sources": [ "build/Release/binding.node" ]
> }
> ]
> }.
> After that, I run node-gyp rebuild command and the issue is solved.

Why did you put a period at the end? It works without the period. Perhaps obvious to some, but not all.

**Comment by djD-REK** [comment] 2020-04-30 23:41
> This is the folder where you need to add a binding.gyp file that contains...
> 
> ```
> {
> 	"targets": [
> 		{
> 			"target_name": "binding",
> 			"sources": [ "build/Release/binding.node" ]
> 		}
> 	]
> }
> ```
> 
> Then try running `node-gyp rebuild` again! Good luck all!

This worked for me.

**Comment by newsfusion** [comment] 2021-01-15 16:04
I had the same issue on Ubuntu 18.04. I needed to switch the python version to 2.7 to solve it:

`update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1`

**Comment by cclauss** [comment] 2021-01-15 16:17
Yeah.  If there are the lines...
```
gyp ERR node -v v0.12.4
gyp ERR node-gyp -v2.0.2
```
... like it says above then you have to use legacy Python because you are using legacy Node and legacy Node-gyp.

Perhaps provide 1. the command that you typed and 2. the full output so that we are not flying blind.

**Comment by fz3hra** [comment] 2021-03-03 19:25
> I create binding.gyp file manually under the path c:\users\leon\appdata\roaming\npm\node_modules\node-gyp with following content:
> {
> "targets": [
> {
> "target_name": "binding",
> "sources": [ "build/Release/binding.node" ]
> }
> ]
> }.
> After that, I run node-gyp rebuild command and the issue is solved.


Please can you tell me how you created the file? Im new to this. I cant figure it out

**Comment by Nisthar** [comment] 2021-04-09 08:28
> I've been running for the same issue for the past few days, here what you need to do :
> 
> * Install python 2.x.x
> * run npm install --global --production windows-build-tools
> * And most important part : don't forget to add **The "binding.gyp" file** in your project folder:
>   check here https://github.com/nodejs/node-gyp#the-bindinggyp-file
> 
> I guess most people (it was my case) forget to simply add binding.gyp
> 
> Hope it helps ...

Isn't this file supposed to be inside the node module that you are installing?

**Comment by TheEhsanSarshar** [comment] 2021-07-29 07:17
I am not sure
maybe this work
`node-gyp configure`
