### ISSUE TITLE
Python version via env variable not supported, or not documented in error stack

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/node-gyp#1388] opened 2018-03-05 20:32 UTC
I am running an `npm install`, and I see this error related to fsevents:

```console
gyp ERR! stack Error: Python executable "/usr/local/bin/python" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)

```

when running npm install, I can't really pass a command line switch to node-gyp TMK, so it would be useful to have an env variable that can do the same thing?

in other words, I am looking for something like this:

```bash
export NODE_GYP_PYTHON_2_PATH=/my/path/to/python_version_2
npm install
```

**Comment by gibfahn** [comment] 2018-03-05 20:39
See https://github.com/nodejs/node-gyp#configuration, does `npm_config_python=/path/to/python` work?

**Comment by jackrex** [comment] 2018-04-18 05:48
use echo "python = /usr/bin/python" >> ~/.npmrc save my life

**Comment by gibfahn** [comment] 2018-04-18 17:27
>use echo "python = /usr/bin/python" >> ~/.npmrc save my life

Yep, that basically tells npm to export the variable. `npm_config_python` variable. The nicer way to do it is:


```bash
npm config set python /usr/bin/python
```

**Comment by maclover7** [comment] 2018-08-01 15:58
Closing since issue with Python location seems to have been resolved :)

**Closed by maclover7** 2018-08-01 15:58 UTC

**Comment by DeeDeeG** [comment] 2020-04-22 22:42
Really short summary: With `node-gyp` 5.1.0, If I have any valid `python`, `python2` or `python3` on my `PATH`, none of the command-line or environment variable-based configuration options work.

(The Python from the `PATH` is preferentially used over any of those configuration options. Configuration options are respected only if no valid Python binary is on the `PATH`.)

Long version below with more details:

---

I am having this problem now. I'm using `node-gyp@5.1.0` as bundled with the latest `npm` (since `npm@6.14.2`).

I can do any of the ways of setting the python path and none stops `node-gyp` from using actual python in the usual location `/usr/bin/python[/2/3]`.
- `npm install --python=[path]`
- `export PYTHON=[path] && npm install`
- `export npm_config_python=[path] && npm install`
  - `npm config set python [path] && npm install`

The previous version of `node-gyp` I was testing with, `node-gyp@3.7.0`, respected any of these options.

---

In fact, I have found that `node-gyp@5.1.0` **will** respect any of these options, as well as the new `export NODE_GYP_FORCE_PYTHON=[path]` option... **only** so long as there is no valid `python`, `python2` or `python3` on the `PATH`. _Then_ `node-gyp@5.1.0` will read from these various configuration options.

(With a valid `python`, `python2` or `python3` on the `PATH`, one of those is ALWAYS used by `node-gyp@5.1.0`.)

---

I tested by having a file `dummy_python.sh` and setting the python path (using all the methods listed above) to point to my dummy python bin. I made the content of my dummy python bin file as follows, so this echo line shows up in `node-gyp`'s error messages:

```sh
#!/bin/bash

echo "Hi from a fake python bin"
```

(I actually made two similar, but not identical dummy files and alternated between them, to make sure I hadn't forgotten to clear a previous configuration and was just seeing the result of the previous one.)

**Comment by DeeDeeG** [comment] 2020-04-23 01:52
Whoops, seems like this is intended behavior -- That is, refusing to use a specified "Python" if that's just a dummy shell script rather than an actual Python binary.

I did `cp /usr/bin/python2 ~/python2` and specified that in all the ways above, and that worked. The python detection is just more advanced than I expected.

Sorry for the spam.
