### ISSUE TITLE
node-gyp starts msbuild twice within windows container for docker via 'npm install bcrypt@^3.0.2'.  Behaves right with 'npm install --build-from-source bcrypt@^3.0.2'

### ISSUE THREAD

**Issue by cdd-aix** [nodejs/node-gyp#1579] opened 2018-10-24 14:39 UTC
* **Node Version**: 
v8.12.0 6.4.1
* **Platform**: 
OS Name:                   Microsoft Windows Server 2016 Standard Evaluation
OS Version:                10.0.14393 N/A Build 14393
System Type:               x64-based PC
(On a windows container from docker derived from microsoft/windowsservercore:ltsc2016)
* **Compiler**: 
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86

* **Module**: bcrypt@3.0.2

<details><summary>
Correct build when run with 'npm install --global --build-from-source bcrypt@^3.0.2'
Fails attempting to run msbuild twice at same time with 'npm install --global bcrypt@^3.0.2'
Specific error message varies from unable to replace an existing file to unable to link to this round's MSB1009.
Error seen less often when using Docker 18.06 CE on Windows 10 than on Docker 18.03.something on Windows 2016 running in a virtualbox VM.

Entire log at https://raw.githubusercontent.com/cdd-aix/nodejs-in-windows-docker/master/docker-buildenvs/node/node-gyp-bug.log

</summary>

```
[0m[91mgyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ContainerAdministrator\\AppData\\Roaming\\npm\\node_modules\\bcrypt\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ContainerAdministrator\\.node-gyp\\8.12.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ContainerAdministrator\\.node-gyp\\8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\ContainerAdministrator\\.node-gyp\\8.12.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\ContainerAdministrator\\AppData\\Roaming\\npm\\node_modules\\bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\ContainerAdministrator\\AppData\\Roaming\\npm\\node_modules\\bcrypt\\build',
gyp info spawn args   '-Goutput_dir=.' ]
[0m[91mgyp [0m[91msill build/config.gypi[0m[91m      tag: 'latest',
gyp [0m[91msill build/config.gypi      tag_version_prefix: 'v',
gyp sill build/config.gypi      timing: '',
gyp sill build/config.gypi      tmp: 'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp',
gyp sill build/config.gypi      umask: '0000',
gyp sill build/config.gypi      unicode: '',
gyp sill build/config.gypi      unsafe_perm: 'true',
gyp sill build/config.gypi      update_notifier: 'true',
gyp sill build/config.gypi      usage: '',
gyp sill build/config.gypi      user: '',
gyp sill build/config.gypi      userconfig: 'C:\\Users\\ContainerAdministrator\\.npmrc',
gyp sill build/config.gypi      user_agent: 'npm/6.4.1 node/v8.12.0 win32 x64',
gyp sill build/config.gypi      version: '',
gyp sill build/config.gypi      versions: '',
gyp sill build/config.gypi      viewer: 'browser' } }
gyp verb build/config.gypi writing out config file: C:\Users\ContainerAdministrator\AppData\Roaming\npm\node_modules\bcrypt\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\ContainerAdministrator\AppData\Roaming\npm\node_modules\bcrypt\config.gypi
[0m[91mgyp verb common.gypi checking for gypi file: C:\Users\ContainerAdministrator\AppData\Roaming\npm\node_modules\bcrypt\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\ContainerAdministrator\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ContainerAdministrator\\AppData\\Roaming\\npm\\node_modules\\bcrypt\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ContainerAdministrator\\.node-gyp\\8.12.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ContainerAdministrator\\.node-gyp\\8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\ContainerAdministrator\\.node-gyp\\8.12.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\ContainerAdministrator\\AppData\\Roaming\\npm\\node_modules\\bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\ContainerAdministrator\\AppData\\Roaming\\npm\\node_modules\\bcrypt\\build',
gyp info spawn args   '-Goutput_dir=.' ]
[0mMSBUILD : error MSB1009: Project file does not exist.
Switch: build/binding.sln
```

</details>

Dockerfile to reproduce the problem available at https://github.com/cdd-aix/nodejs-in-windows-docker/blob/master/docker-buildenvs/node/Dockerfile-node-gyp-bug

Reproduce with
```
docker build --no-cache -m 2G -f Dockerfile-node-gyp-bug .
```

Reproduces with vs2015 and vs2017.

Use Stefan Scherer's windows-docker-machine to reproduce from Mac or Linux host.
Follow the README at https://github.com/StefanScherer/windows-docker-machine and use '2016-box'.

**Comment by bnoordhuis** [comment] 2018-11-09 20:04
Closing, not a node-gyp bug. The issue is with bcrypt's install script / node-pre-gyp (different project.)

**Closed by bnoordhuis** 2018-11-09 20:04 UTC
