### ISSUE TITLE
Error finding node-gyp module

### ISSUE THREAD

**Issue by maketroli** [nodejs/node-gyp#1239] opened 2017-06-19 23:41 UTC
So well, is incredible how ALWAYS, on every single variation of Node, there is node-gyp to give us a headache.

```
Error: Cannot find module '/Users/Marcelo/Desktop/TestDig/promo-ways-to-invest/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Build failed
```

I already check, delete, installed and whatever possibilities exists, and I can't fix the issue.
I already installed and uninstalled Node, NPM and every related to it in my computer.

I am on macOS El Capitan:
Node: 6.0.0
Npm: 5.0.3

I have fixed that error the last year like here: https://github.com/sass/node-sass/issues/1432#issuecomment-209661374.

```
sudo npm install -g n
sudo n 0.12.7
sudo npm install node-sass@2
sudo npm -g install node-gyp@3
sudo npm rebuild node-sass 
``` 

And in order to fixed it, as you see the in that issue, I had to get back to node `0.12.7`. Ridiculous.
I've been on this for the last 2 hours and I can't even believe it.

Here my package json:
```
{
  "name": "waystoinvest",
  "app": "app",
  "dist": "dist",
  "version": "0.0.0",
  "dependencies": {
    "bower": "~1.3.9",
    "node-sass": "^4.5.3"
  },
  "devDependencies": {
    "assemble": "~0.4.37",
    "grunt": "~0.4.1",
    "grunt-autoprefixer": "~1.0.1",
    "grunt-bower-install": "~1.4.0",
    "grunt-concurrent": "~0.5.0",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-compress": "~0.8.0",
    "grunt-contrib-concat": "~0.4.0",
    "grunt-contrib-connect": "~0.7.1",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-htmlmin": "~0.2.0",
    "grunt-contrib-imagemin": "~0.7.0",
    "grunt-contrib-jshint": "~0.9.2",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-exec": "~0.4.5",
    "grunt-notify": "^0.3.0",
    "grunt-rev": "~0.1.0",
    "grunt-sass": "0.18.1",
    "grunt-stripmq": "~0.0.4",
    "grunt-svgmin": "~0.4.0",
    "grunt-usemin": "~2.1.1",
    "grunt-wiredep": "^1.7.0",
    "load-grunt-tasks": "~0.4.0",
    "node-gyp": "^3.6.2",
    "time-grunt": "~0.3.1"
  },
  "engines": {
    "node": ">=4.0.0"
  }
}
```

So, are your suggestions?

**Comment by gibfahn** [comment] 2017-06-20 06:40
Is there a reason you have `node-gyp` in your dependencies? It's bundled with npm, you should never need to install it.

**Comment by gibfahn** [comment] 2017-06-20 06:44
Also what command did you run? Is `waystoinvest` a native app?

**Comment by gibfahn** [comment] 2017-06-20 06:48
I'm running macOS Sierra, using `nvm`, and I've never had an issue like this with node-gyp. So this must be a solvable problem!

If I do:

```bash
➜  tmp ❯ nvm use 6                                                                             ~/tmp
npm i Now using node v6.11.0 (npm v3.10.10)
➜  tmp ❯ npm i bcrypt                                                                          ~/tmp

> bcrypt@1.0.2 install /Users/gib/tmp/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.11.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  COPY /Users/gib/tmp/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
/Users/gib/tmp
└─┬ bcrypt@1.0.2 
  ├── bindings@1.2.1 
  ├── nan@2.5.0 
  └─┬ node-pre-gyp@0.6.32 
    ├─┬ rc@1.1.7 
    │ ├── deep-extend@0.4.2 
    │ ├── ini@1.3.4 
    │ └── strip-json-comments@2.0.1 
    ├── rimraf@2.5.4 
    └─┬ tar-pack@3.3.0 
      ├─┬ debug@2.2.0 
      │ └── ms@0.7.1 
      ├── fstream-ignore@1.0.5 
      ├── once@1.3.3 
      ├─┬ readable-stream@2.1.5 
      │ ├── buffer-shims@1.0.0 
      │ └── string_decoder@0.10.31 
      ├── rimraf@2.5.4 
      └── uid-number@0.0.6 
```

then `node-gyp` compiles that native app. Does this work for you?

**Comment by gibfahn** [comment] 2017-06-20 06:50
Also when I do `npm i node-sass` it just uses a prebuilt binary, and doesn't even need `node-gyp`.

```bash
➜  tmp ❯ npm i node-sass                                                                       ~/tmp

> node-sass@4.5.3 install /Users/gib/tmp/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-48_binding.node
Download complete░░⸩ ⠋ :
Binary saved to /Users/gib/tmp/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Caching binary to /Users/gib/.cache/npm/node-sass/4.5.3/darwin-x64-48_binding.node

> node-sass@4.5.3 postinstall /Users/gib/tmp/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/gib/tmp/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Testing binary
Binary is fine
/Users/gib/tmp
└─┬ node-sass@4.5.3 
```

So if you could be more specific about what you're actually running that'd be helpful.

Also can you use `6.11.0`?

**Comment by bnoordhuis** [comment] 2017-06-20 08:55
This:

> promo-ways-to-invest/node_modules/node-sass/node_modules/pangyp/bin/node-gyp

Suggests the issue is with [pangyp](https://www.npmjs.com/package/pangyp), not node-gyp.  Since pangyp is deprecated, you (or node-sass) should stop using it.

I'll close this out as there is no indication it's actually a node-gyp issue.

**Closed by bnoordhuis** 2017-06-20 08:55 UTC
