### ISSUE TITLE
node-gyp rebuild: Error: spawn ENOENT 

### ISSUE THREAD

**Issue by egroj55** [nodejs/node-gyp#559] opened 2015-01-07 13:46 UTC
Hi, have tried to install my custom Yeoman generator on Windows 8,
Usally I use Fedora or other unix based systems, but had do use Windows for this project.

Now when I try to run npm link from my generator directory I get this error:

```
c:\Apache24\htdocs\generator\node_modules\exec-sync\node_modules\ffi\node_module
s\ref>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\nod
e_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Apache24\htdocs\generator\node_modules\exec-sync\node_modules\ff
i\node_modules\ref
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "link"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE

npm ERR! ref@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@0.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Apache24\htdocs\generator\npm-debug.log
```

I have tried doing this in the command promts (Windows original,node,ruby and as a Administrator) and Git bash but keep getting this same error.

Doing npm install node-gyp works fine, this error persist when I'm trying to do npm link. I also have a npm-debug.log that I can attach if its helpful.

My user has Full controll for the directory and Sub-directoies in C:\Program Files\nodejs
I had Python 2.7.8 but changed to 2.7.3 as recommended in the installation description (Python is in my Path).
Also have Microsoft Visual Studio C++ 2012/13 for Windows Desktop Express.

What am I doing wrong here?

**Comment by srossross** [comment] 2015-03-17 15:23
I am getting a similar error trying to install a 3rd party package. 

```
+ npm install authenticate
npm WARN package.json wnext@0.0.0 No repository field.
|
> authenticate-pam@0.2.2 install /Users/sean/Documents/workspace/wnext/node_modules/authenticate-pam
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/sean/anaconda/envs/_build/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sean/Documents/workspace/wnext/node_modules/authenticate-pam
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

**Comment by srossross** [comment] 2015-03-17 15:27
Here is the node version information, printed before the error:

```
+ which node
/Users/sean/anaconda/envs/_build/bin/node
+ node --version
v0.10.35
```

**Comment by egroj55** [comment] 2015-03-17 20:54
Sorry I haven't resolved this issue yet for windows, I'm suddenly on OS X now. Had a similar trouble though the first time with node on this laptop, but not any more. Probably some dependency issue.

**Comment by maclover7** [comment] 2018-07-20 18:40
@egroj55 @srossross Are you able to reproduce this on a more recent version of node-gyp?

**Comment by jorgeuos** [comment] 2018-07-21 09:43
Sorry, Haven't used windows since that project I believe. Usually a `nvm use` to the correct version of node and `npm rebuild node-sass` fixes these kind of problems.

**Comment by maclover7** [comment] 2018-07-22 00:48
👍 will close this out then

**Closed by maclover7** 2018-07-22 00:48 UTC
