### ISSUE TITLE
Need better /MD multithreaded dll support

### ISSUE THREAD

**Issue by AlexAtNet** [nodejs/node-gyp#330] opened 2013-09-13 14:24 UTC
I'm trying to compile the node.js extension with the following binding.gyp file:

```
{
  "targets": [
    {
      "target_name": "MyLib",
      "type": "shared_library",
      "sources": [ ... ],
      "conditions": [
        [ "OS=='win'", { "libraries": [
          "..\\Library\\binaries\\x64\\Release\\mylib.lib"
        ] } ]
      ]
    }
  ]
}
```

and VS2012 Pro. The command line is following:

```
node-gyp configure --msvs_version=2012 && node-gyp build
```

This causes the error:

```
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease'
```

Changing the property "RuntimeLibrary" in the vcxproj  file from "MultiThreaded" to "MultiThreadedDLL" fixes compilation.

Is it correct workaround?

Thanks,
Alex

**Comment by saper** [comment] 2015-09-07 20:38
Is it some variant of #26 really? I cannot override `ExceptionHandling` and `RuntimeTypeInfo` in my gyp file - always the global node values are used unless I do MSVS flags by hand.

**Comment by toddwong** [comment] 2017-11-22 14:00
It's painful to use /MT actually. I have to change almost all the third party libraries's building script to fit this requirements (they all use the default VS setting defaultly).

**Comment by claytongulick** [comment] 2018-07-10 19:07
I'm running into a similar issue while trying to build a debug node addon with OpenCV. OpenCV uses DLL distribution and linking with static CRT causes assertion errors when deallocating std::vector. For now, to fix the issue, I've added /MDd to "AdditionalOptions" in binding.gyp, but like @springmeyer mentioned, this creates a lot of warnings.

**Comment by saper** [comment] 2018-07-11 09:43
Are you building also your own node engine with those options?

**Comment by claytongulick** [comment] 2018-07-11 15:21
@saper no, but I've had no trouble linking to x64 versions of node debug build and nw.js like this (using nw-gyp).

**Comment by saper** [comment] 2018-07-12 23:22
Yes, I mean it may link, but is this a proper way at all? Exception handling needs to be properly initialized for a whole application. I don't know exactly how startup code changes with `/MT` but I understand that changes are non-trivial:

> Causes the application to use the multithread-specific and DLL-specific version of the run-time library. Defines _MT and _DLL and causes the compiler to place the library name MSVCRT.lib into the .obj file.

so we get a different runtime library.

I've had a quick look at node's own [common.gypi](https://github.com/nodejs/node/blob/e7a18c5bf132ff0e3f9ccb702ff7628eaf214865/common.gypi#L186) and it will use `/MD` when selecting `Release` configuration" (or `/MDd` for `Debug`) provided node is built to use shared libraries instead of burned-in libraries like OpenSSL: 

````python
          ['node_shared=="true"', {
            'msvs_settings': {
             'VCCLCompilerTool': {
               'RuntimeLibrary': 2 # MultiThreadedDLL (/MD)
             }
            }
}],
````

Can you [rebuild your Windows node](https://github.com/nodejs/node/blob/e7a18c5bf132ff0e3f9ccb702ff7628eaf214865/BUILDING.md#windows-1) with

    vcbuild dll

make sure `node-gyp` sees your node build directory with `--nodedir` and see if that helps?

    node -p process.config.variables.node_shared

should give `true` and therefore `node-gyp` should use node settings for the modules.

You might unfortunately have provide pre-built external libraries for this, I haven't checked this.

**Comment by claytongulick** [comment] 2018-07-13 00:16
@saper if I understand the issue correctly (which I probably don't) the problem is that the project template that's being created when we pass --debug selects the MT static libs (this can be seen by just opening the project in visual studio and looking at the link settings). This seems to be incorrect - so the workaround to override those default project settings is to switch to the correct runtime, right? We can do that via an override /MDd option, or by switching the runtime engine (above) - I'm with you, I don't really know if /MDd does anything special other than setting the debug dll engine, but the docs seem to indicate that's all it does - But still, the root cause seems to be an incorrect project template with the --debug flag. That should be fixed, no?

**Comment by saper** [comment] 2018-07-13 03:41
The project template is generated out of few things, one of them are Visual Studio flags used to build node engine itself. node-gyp (`addon.gypi`) and the addon (`binding.gyp`) provide only some extra settings. Most of it is determined by the node engine configuration itself.

The settings possible seem to be the following:

vcbuild parameter | `process.config.variables.node_shared` | Debug/Release | Resulting flag
---------------------------- | --------------------------- | ------------------------- | -----
(none) | false | `Release` | `/MT`
`dll` | true | `Release` | `/MD`
`debug` | false | `Debug` | `/MTd`
`debug dll` | true |  `Debug` | `/MDd`

(this is based on my understanding of [common.gypi](https://github.com/nodejs/node/blob/e7a18c5bf132ff0e3f9ccb702ff7628eaf214865/common.gypi#L186), I haven't tested the above

**Comment by saper** [comment] 2019-10-22 00:36
I think this can be closed - looks like we do provide `/MD` support if one builds node that way.

**Closed** 2019-10-22 02:09 UTC
Labels: Multiple Reports, Windows
