### ISSUE TITLE
Unable to run `node-gyp configure`

### ISSUE THREAD

**Issue by jakobrosenberg** [nodejs/node-gyp#3054] opened 2024-08-01 19:35 UTC
* **Node Version**:
* 22.5.1 / 10.8.2
* **Platform**: 
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
System Type:               x64-based PC
* **Compiler**: 
cl: The term 'cl' is not recognized as a name of a cmdlet
msbuild: The term 'msbuild' is not recognized as a name of a cmdlet

* **Module**:
I get the error even if I run `node-gyp configure` in a an empty folder after running `npm init`

<details><summary>Verbose output (from npm or node-gyp):</summary>

gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli 'C:\\Users\\jakob\\AppData\\Local\\Volta\\tools\\image\\node\\22.5.1\\node.exe',
gyp verb cli 'C:\\Users\\jakob\\AppData\\Local\\Volta\\tools\\image\\packages\\node-gyp\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli 'rebuild',
gyp verb cli '--verbose'
gyp verb cli ]
gyp info using node-gyp@10.2.0
gyp info using node@22.5.1 | win32 | x64
gyp verb clean removing "build" directory
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if the py launcher can be used to find Python 3
gyp verb find Python - executing "py.exe" to get Python 3 executable path
gyp verb find Python - executable path is "C:\Users\jakob\AppData\Local\Programs\Python\Python39\python.exe"
gyp verb find Python - executing "C:\Users\jakob\AppData\Local\Programs\Python\Python39\python.exe" to get version
gyp verb find Python - version is "3.9.6"
gyp info find Python using Python version 3.9.6 found at "C:\Users\jakob\AppData\Local\Programs\Python\Python39\python.exe"  
gyp verb get node dir no --target version specified, falling back to host node version: 22.5.1

gyp verb install input version string "22.5.1"
gyp verb install installing version: 22.5.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 11
gyp verb needs "installVersion" 11
gyp verb install version is good
gyp verb on Windows; need to check node.lib
gyp verb get node dir target node version installed: 22.5.1
gyp verb build dir attempting to create "build" dir: C:\Users\jakob\temp\08\empty\build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
gyp verb find VS
gyp verb find VS Failure details: undefined
gyp verb find VS unsupported version "15.9.28307.1622" found at "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS checking VS2022 (17.10.35122.118) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v143
gyp verb find VS - found Windows SDK: 10.0.22621.0
gyp info find VS using VS2022 (17.10.35122.118) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\jakob\temp\08\empty\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\jakob\temp\08\empty\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\jakob\temp\08\empty\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\jakob\AppData\Local\Programs\Python\Python39\python.exe
gyp info spawn args [
gyp info spawn args 'C:\\Users\\jakob\\AppData\\Local\\Volta\\tools\\image\\packages\\node-gyp\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\jakob\\temp\\08\\empty\\build\\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\jakob\\AppData\\Local\\Volta\\tools\\image\\packages\\node-gyp\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\jakob\\AppData\\Local\\node-gyp\\Cache\\22.5.1\\include\\node\\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\\Users\\jakob\\AppData\\Local\\node-gyp\\Cache\\22.5.1',
gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\jakob\\AppData\\Local\\Volta\\tools\\image\\packages\\node-gyp\\node_modules\\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\jakob\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.5.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args '-Dmodule_root_dir=C:\\Users\\jakob\\temp\\08\\empty',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'C:\\Users\\jakob\\temp\\08\\empty\\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Users\jakob\temp\08\empty) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\jakob\AppData\Local\Volta\tools\image\packages\node-gyp\node_modules\node-gyp\lib\configure.js:317:18)
gyp ERR! stack at ChildProcess.emit (node:events:520:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "C:\\Users\\jakob\\AppData\\Local\\Volta\\tools\\image\\node\\22.5.1\\node.exe" "C:\\Users\\jakob\\AppData\\Local\\Volta\\tools\\image\\packages\\node-gyp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
gyp ERR! cwd C:\Users\jakob\temp\08\empty
gyp ERR! node -v v22.5.1
gyp ERR! node-gyp -v v10.2.0
gyp ERR! not ok

</details>

Have also tried Node 17, but same error.

**Comment by cclauss** [comment] 2024-08-01 20:39
> gyp: binding.gyp not found (cwd: C:\Users\jakob\temp\08\empty) while trying to load binding.gyp

Need a `binding.gyp` file?
* https://github.com/nodejs/node-gyp?tab=readme-ov-file#how-to-use
* https://github.com/nodejs/node-gyp/blob/main/docs/binding.gyp-files-in-the-wild.md

**Comment by StefanStojanovic** [comment] 2024-10-29 11:54
As explained in the previous comment, the issue is a missing `bindings.gyp` file. Closing this.

**Closed by StefanStojanovic** 2024-10-29 11:54 UTC
