### ISSUE TITLE
Cannot build hello-world example: "Completion callback never invoked!"

### ISSUE THREAD

**Issue by evanw** [nodejs/node-gyp#545] opened 2014-12-07 19:17 UTC
I was trying to build the hello-world example at https://github.com/joyent/node/tree/master/test/addons/hello-world and got this error:

```
$ node-gyp rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [ 'node', '/usr/local/bin/node-gyp', 'rebuild', '--verbose' ]
gyp info using node-gyp@0.6.10
gyp info using node@0.10.33 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded for `%s` python /usr/bin/python
gyp verb check python version `python -c "import platform; print platform.python_version();"` returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: v0.10.33
gyp verb command install [ 'v0.10.33' ]
gyp verb install input version string "v0.10.33"
gyp verb installing legacy version? false
gyp verb install installing version: 0.10.33
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 0
gyp verb needs "installVersion" 9
gyp verb install version is no good; reinstalling
gyp verb ensuring nodedir is created /Users/evan/.node-gyp/0.10.33
gyp http GET http://nodejs.org/dist/v0.10.33/node-v0.10.33.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.33/node-v0.10.33.tar.gz
gyp verb extracted file from tarball deps/openssl/buildinf.h
gyp verb extracted file from tarball deps/openssl/config/opensslconf.h
gyp ERR! Completion callback never invoked! 
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild" "--verbose"
gyp ERR! cwd /Users/evan/Desktop/hello-world
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.6.10
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
```

I re-installed the latest version of node just in case, but it didn't help. Operating system: OS X Yosemite 10.10.1.

**Comment by maboiteaspam** [comment] 2015-01-01 06:45
hello,

same here

```
maboiteaspam [14:40:01] cozy-light  node-gyp rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [ 'node',
gyp verb cli   '/home/maboiteaspam/bin/node-gyp',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@1.0.2
gyp info using node@0.10.33 | linux | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `python -c "import platform; print(platform.python_version());"` returned: "2.7.8\n"
gyp verb get node dir no --target version specified, falling back to host node version: v0.10.33
gyp verb command install [ 'v0.10.33' ]
gyp verb install input version string "v0.10.33"
gyp verb install installing version: 0.10.33
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 0.10.33
gyp verb ensuring nodedir is created /home/maboiteaspam/.node-gyp/0.10.33
gyp verb created nodedir /home/maboiteaspam/.node-gyp/0.10.33
gyp http GET http://nodejs.org/dist/v0.10.33/node-v0.10.33.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.33/node-v0.10.33.tar.gz
gyp verb extracted file from tarball deps/openssl/buildinf.h
gyp verb extracted file from tarball deps/openssl/config/opensslconf.h
gyp verb extracted file from tarball deps/openssl/openssl/e_os.h
gyp verb extracted file from tarball deps/openssl/openssl/ms/tlhelp32.h
gyp verb extracted file from tarball deps/openssl/openssl/ms/uplink.h
gyp verb extracted file from tarball deps/openssl/openssl/test/testutil.h
gyp verb extracted file from tarball deps/openssl/openssl/MacOS/opensslconf.h
gyp verb extracted file from tarball deps/openssl/openssl/MacOS/Randomizer.h
gyp verb extracted file from tarball deps/openssl/openssl/MacOS/_MWERKS_prefix.h
gyp verb extracted file from tarball deps/openssl/openssl/MacOS/GetHTTPS.src/MacSocket.h
gyp verb extracted file from tarball deps/openssl/openssl/MacOS/_MWERKS_GUSI_prefix.h
gyp verb extracted file from tarball deps/openssl/openssl/MacOS/buildinf.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/ssl_locl.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/ssl2.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/kssl_lcl.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/ssl3.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/dtls1.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/ssl23.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/kssl.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/srtp.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/ssl.h
gyp verb extracted file from tarball deps/openssl/openssl/ssl/tls1.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/e_atalla_err.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/e_sureware_err.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/vendor_defns/hw_4758_cca.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/vendor_defns/sureware.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/vendor_defns/atalla.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/vendor_defns/cswift.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/vendor_defns/hw_ubsec.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/vendor_defns/hwcryptohook.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/vendor_defns/aep.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/e_chil_err.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/e_capi_err.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/e_gmp_err.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/e_ubsec_err.h
gyp verb extracted file from tarball deps/openssl/openssl/engines/e_cswift_err.h
gyp verb content checksum node-v0.10.33.tar.gz d566b6e585d0f3a372ab2208049efae870e46b94d97e1ab6dc2361ee61c350d0
gyp verb extracted file from tarball deps/openssl/openssl/engines/e_aep_err.h
gyp ERR! Completion callback never invoked! 
gyp ERR! System Linux 3.16.0-28-generic
gyp ERR! command "node" "/home/maboiteaspam/bin/node-gyp" "rebuild" "--verbose"
gyp ERR! cwd /home/maboiteaspam/Bureau/cozy-light
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
maboiteaspam [14:43:40] cozy-light  node -v
v0.10.33
```

**Comment by tk120404** [comment] 2018-03-14 05:49
@evanw Is this still an issue, Can we close this if this not an issue any more?

**Comment by maclover7** [comment] 2018-08-01 01:41
Are you able to reproduce this on a more recent version of node-gyp?

**Comment by maclover7** [comment] 2018-08-08 15:36
Closing due to inactivity, please feel free to reopen if you are able to reproduce on a more recent version of node-gyp :)

**Closed by maclover7** 2018-08-08 15:36 UTC
