### ISSUE TITLE
npm error code 1

### ISSUE THREAD

**Issue by changzhiqiang84** [nodejs/node-gyp#3111] opened 2024-12-25 02:40 UTC
PS D:\source\czq\20241218\Angular18> npm install ffi-napi --legacy-peer-deps 
npm warn deprecated gar@1.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm error code 1
npm error path D:\source\czq\20241218\Angular18\node_modules\ffi-napi
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node-gyp-build
npm error nothing.c
npm error   win_delay_load_hook.cc
npm error   nothing.vcxproj -> D:\source\czq\20241218\Angular18\node_modules\ffi-napi\build\Release\\nothing.lib
npm error   Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
npm error   '"call"' は、内部コマンドまたは外部コマンド、
npm error   操作可能なプログラムまたはバッチ ファイルとして認識されていません。
npm error D:\source\czq\20241218\Angular18\node_modules\ffi-napi\build\deps\libffi\ffi.targets(34,5): error MSB3721: コマンド "call "call" "../../../deps/libffi/preprocess_asm.cmd" "../../../deps/libffi/include" "../../../deps/libffi/config/win/x64" "..\..\..\deps\libffi\src\x86\win64_intel.preasm" "Release\obj\ffi\win64_intel.asm"" はコード 1 で終了しました。 [D:\source\czq\20241218\Angular18\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.0.0
npm error gyp info using node@18.20.5 | win32 | x64
npm error gyp info find Python using Python version 3.13.1 found at "C:\Users\changzq\AppData\Local\Programs\Python\Python313\python.exe"
npm error gyp info find VS using VS2022 (17.12.35527.113) found at:
npm error gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Users\changzq\AppData\Local\Programs\Python\Python313\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'D:\\source\\czq\\20241218\\Angular18\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'msvs',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'D:\\source\\czq\\20241218\\Angular18\\node_modules\\ffi-napi\\build\\config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'D:\\source\\czq\\20241218\\Angular18\\node_modules\\node-gyp\\addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\changzq\\AppData\\Local\\node-gyp\\Cache\\18.20.5\\include\\node\\common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=C:\\Users\\changzq\\AppData\\Local\\node-gyp\\Cache\\18.20.5',
npm error gyp info spawn args '-Dnode_gyp_dir=D:\\source\\czq\\20241218\\Angular18\\node_modules\\node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\changzq\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.20.5\\\\<(target_arch)\\\\node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=D:\\source\\czq\\20241218\\Angular18\\node_modules\\ffi-napi',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'D:\\source\\czq\\20241218\\Angular18\\node_modules\\ffi-napi\\build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'build\\binding.sln',
npm error gyp info spawn args '/clp:Verbosity=minimal',
npm error gyp info spawn args '/nologo',
npm error gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm error gyp info spawn args ]
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (D:\source\czq\20241218\Angular18\node_modules\node-gyp\lib\build.js:216:23)
npm error gyp ERR! stack at ChildProcess.emit (node:events:517:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm error gyp ERR! System Windows_NT 10.0.19045
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\source\\czq\\20241218\\Angular18\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm error gyp ERR! cwd D:\source\czq\20241218\Angular18\node_modules\ffi-napi
npm error gyp ERR! node -v v18.20.5
npm error gyp ERR! node-gyp -v v11.0.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: C:\Users\changzq\AppData\Local\npm-cache\_logs\2024-12-25T01_43_55_397Z-debug-0.log

**Comment by cclauss** [comment] 2024-12-25 04:13
Duplicate of
* node-ffi-napi/node-ffi-napi#269

https://github.com/nodejs/node-gyp/labels/ffi-napi

**Closed by cclauss** 2024-12-25 04:13 UTC
Labels: ffi-napi
