### ISSUE TITLE
node-gyp with Windows 10 and Visual Studio 2015

### ISSUE THREAD

**Issue by Gabriel0402** [nodejs/node-gyp#698] opened 2015-08-20 21:25 UTC
When I'm installing node-gyp in windows 10 with visual studio 2015, there's an error which says that binding.gyp not found. I've installed python27 and set the path in node-gyp. I also install the windows10 sdk which is in C:\Program Files (x86)\Windows Kits\10. But the error still exists. Any help?

**Comment by pinin** [comment] 2015-08-21 01:58
a very long way for widows - there are missing files

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\npm\  .... just missing .... node_modules\node-gyp\bin\...

**Comment by Jayflux** [comment] 2015-09-29 10:39
hi @Gabriel0402 @pinin 
I think this ticket is a duplicate of https://github.com/nodejs/node-gyp/issues/679 which is where the main conversation of this problem is taking place

**Comment by Jayflux** [comment] 2015-10-12 09:34
Can we close this ticket as its a duplicate of https://github.com/nodejs/node-gyp/issues/679
If anyone has issues can you please discuss them there instead
Thanks

**Comment by dado3212** [comment] 2017-09-19 05:20
This is a different error.  It's "binding.gyp".

**Closed** 2017-09-19 09:50 UTC
Labels: Windows
