### ISSUE TITLE
Unable to build for Raspberry Pi 3|B

### ISSUE THREAD

**Issue by AkshayKanchan** [nodejs/node-gyp#1886] opened 2019-09-23 19:14 UTC
All of sudden my project stopped working on raspberry pi so I tried re-installing the dependencies, while rebuilding using electron-rebuild I am facing below problem.
 
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | linux | arm
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://electronjs.org/headers/v6.0.10/node-v6.0.10-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v6.0.10/node-v6.0.10-headers.tar.gz
gyp ERR! Completion callback never invoked! 
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/home/pi/projects/electrion_rpi/node_modules/.bin/node-gyp" "rebuild" "--target=6.0.10" "--arch=arm" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/pi/projects/electrion_rpi/node_modules/epoll
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 6

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | linux | arm
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://electronjs.org/headers/v6.0.10/node-v6.0.10-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v6.0.10/node-v6.0.10-headers.tar.gz
gyp ERR! Completion callback never invoked! 
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/home/pi/projects/electrion_rpi/node_modules/.bin/node-gyp" "rebuild" "--target=6.0.10" "--arch=arm" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/pi/projects/electrion_rpi/node_modules/epoll
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 6
    at SafeSubscriber._error (/home/pi/projects/electrion_rpi/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/projects/electrion_rpi/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/pi/projects/electrion_rpi/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/pi/projects/electrion_rpi/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/pi/projects/electrion_rpi/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/pi/projects/electrion_rpi/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/pi/projects/electrion_rpi/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/pi/projects/electrion_rpi/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/pi/projects/electrion_rpi/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/pi/projects/electrion_rpi/node_modules/rxjs/internal/Subscriber.js:143:22)

**Comment by amirburbea** [comment] 2019-09-23 21:17
Having the same problem on windows

**Comment by brianjjones** [comment] 2019-09-24 00:58
Having the same issue on ubuntu. Reverting to an older version did not solve the issue.

**Comment by leonschwanitz** [comment] 2019-09-24 01:20
Having the same issue on windows!

**Comment by jonatzipwhip** [comment] 2019-09-24 03:06
reasonably pure repro:
```
➜  github docker create -t -i node:alpine sh
2ef1684afc1f3ac57c713fbe313b7f7e0a0f1686c8680c2712a7d3c7acc6a20a
➜  github docker start -a -i 2ef1684afc1f3ac57c713fbe313b7f7e0a0f1686c8680c2712a7d3c7acc6a20a
/ # apk add python; npm install node-gyp -g; node-gyp rebuild
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/10) Installing libbz2 (1.0.6-r7)
(2/10) Installing expat (2.2.8-r0)
(3/10) Installing libffi (3.2.1-r6)
(4/10) Installing gdbm (1.13-r1)
(5/10) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(6/10) Installing ncurses-terminfo (6.1_p20190105-r0)
(7/10) Installing ncurses-libs (6.1_p20190105-r0)
(8/10) Installing readline (7.0.003-r1)
(9/10) Installing sqlite-libs (3.28.0-r0)
(10/10) Installing python2 (2.7.16-r1)
Executing busybox-1.29.3-r10.trigger
OK: 54 MiB in 26 packages
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@5.0.3
added 98 packages from 67 contributors in 5.427s
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.10.0 | linux | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v12.10.0/node-v12.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.10.0/node-v12.10.0-headers.tar.gz
gyp ERR! Completion callback never invoked!
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
/ # %                                                                                                                                                                   ➜  github docker rm 2ef1684afc1f3ac57c713fbe313b7f7e0a0f1686c8680c2712a7d3c7acc6a20a
2ef1684afc1f3ac57c713fbe313b7f7e0a0f1686c8680c2712a7d3c7acc6a20a
➜  github
```
Any idea's on best way to debug?

**Comment by kyleoneill** [comment] 2019-09-24 16:42
Issue #1887 references this same issue and it seems to have been a server issue, try it again and see if it's been resolved

**Comment by mmarchini** [comment] 2019-09-24 17:43
Duplicate of https://github.com/nodejs/node-gyp/issues/1887. See https://github.com/nodejs/node-gyp/issues/1887#issuecomment-534669347 for context on what happened.

**Closed by mmarchini** 2019-09-24 17:43 UTC
