### ISSUE TITLE
would it be possible (or impossible) to use mingw-64 instead of visual studio on Windows ?

### ISSUE THREAD

**Issue by stonebig** [nodejs/node-gyp#660] opened 2015-07-07 18:52 UTC
My detail use-case is described here; https://github.com/willwhitney/hydrogen/issues/79

**Comment by justinmchase** [comment] 2015-07-09 03:37
Possible duplicate of #194

**Comment by stonebig** [comment] 2015-07-09 04:20
I don't use MSYS, so it's worse than that.

**Comment by stonebig** [comment] 2015-08-30 17:13
using mingwpy as a possible target compiler of node-gyp may be a simple way to resolve the general issue #629

**Comment by bnoordhuis** [comment] 2015-08-30 17:27
The short answer is 'no': mingw is not supported by gyp and its C++ symbol mangling is incompatible with VS.  Even if you got it to compile, you wouldn't be able to load the resulting add-on in node (which is built with VS.)

**Closed by bnoordhuis** 2015-08-30 17:27 UTC
Labels: Windows
