### ISSUE TITLE
npm install gyp diskusage error

### ISSUE THREAD

**Issue by projectje** [nodejs/node-gyp#1948] opened 2019-10-27 22:42 UTC
npm install with node v12,10,0, gyp v3.8.0 , building npm diskusage, win64 machine. 

yp\bin\node-gyp.js" rebuild ) else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\repo\node_modules\node\bin\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\repo\node_modules\diskusage
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in node-gyp.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR! https://github.com/nodejs/node-gyp/issues
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! diskusage@1.1.3 install: node-gyp rebuild
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the diskusage@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\gebruiker\AppData\Roaming\npm-cache_logs\2019-10-27T22_05_08_292Z-debug.log

**Comment by projectje** [comment] 2019-10-27 22:52
I reinstalled a lot of stuff and I think.. I'm now at https://github.com/nodejs/node-gyp/issues/1933 , getting the 403 error of the other issue.
So as far as I can read there I have to wait for this.

**Comment by bnoordhuis** [comment] 2019-11-03 09:31
This error:

> gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT

Indeed suggests something was off with your VS install. I'll close this out as a now-duplicate of #1933, cheers.

**Closed by bnoordhuis** 2019-11-03 09:31 UTC
