### ISSUE TITLE
Replace deprecated request

### ISSUE THREAD

**Issue by guimard** [nodejs/node-gyp#2252] opened 2020-11-04 16:29 UTC
Hi,

`request` is [deprecated](https://github.com/request/request/issues/3142), you should replace it by [node-fetch](https://www.npmjs.com/package/node-fetch), [axios](https://www.npmjs.com/package/axios),...

**Comment by richardlau** [comment] 2020-11-04 16:34
Duplicate of https://github.com/nodejs/node-gyp/issues/2047.

**Closed by richardlau** 2020-11-04 16:34 UTC
