### ISSUE TITLE
MSbuild error everytime, i tried everything ( image provided)

### ISSUE THREAD

**Issue by uaedronemaster** [nodejs/node-gyp#841] opened 2015-12-11 17:35 UTC
![captuscsadqre](https://cloud.githubusercontent.com/assets/16239818/11750854/25b1d3f6-a04f-11e5-9a9d-ad80d673287c.PNG)

**Comment by saper** [comment] 2016-01-08 02:06
This is some problem with Oculus SDK and the node module, it is not caused by node-gyp.

**Comment by bnoordhuis** [comment] 2016-04-28 12:48
Closing, not a node-gyp issue.

**Closed by bnoordhuis** 2016-04-28 12:48 UTC
