### ISSUE TITLE
gyp ERR! stack Error: 403 status code downloading arm64 node.lib

### ISSUE THREAD

**Issue by petervanderwalt** [nodejs/node-gyp#2023] opened 2020-01-15 16:44 UTC
I have a CI setup that has been virtually anchanged for months, suddenly today, it errors out, cannot download arm64 node.lib. 

Nothing changed on our end related to this, so, something on the server hosting node.libs are giving 403s - please fix

```
 electron-builder install-app-deps
  • electron-builder version=20.43.0
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:
> serialport@6.2.2 install C:\projects\openbuilds-control\node_modules\avrgirl-arduino\node_modules\serialport
> prebuild-install || node-gyp rebuild
C:\projects\openbuilds-control\node_modules\avrgirl-arduino\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Error output:
prebuild-install WARN install No prebuilt binaries found (target=4.2.3 runtime=electron arch=x64 platform=win32)
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 status code downloading arm64 node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:335:22)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:454:20)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\openbuilds-control\node_modules\avrgirl-arduino\node_modules\serialport
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2020-01-15T16_34_33_495Z-debug.log
    at ChildProcess.childProcess.once.code (C:\projects\openbuilds-control\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at _rebuild (C:\projects\openbuilds-control\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\projects\openbuilds-control\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\projects\openbuilds-control\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (C:\projects\openbuilds-control\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\projects\openbuilds-control\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\projects\openbuilds-control\node_modules\electron-builder\src\cli\install-app-deps.ts:59:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! OpenBuildsCONTROL@1.0.205 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the OpenBuildsCONTROL@1.0.205 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2020-01-15T16_34_33_656Z-debug.log
Command exited with code 1
```

</details>

History: https://ci.appveyor.com/project/openbuilds-engineer/openbuilds-control/history

**Comment by richardlau** [comment] 2020-01-15 16:56
Duplicate of https://github.com/nodejs/node-gyp/issues/1933. It was fixed in node-gyp 5.0.6 (or 6.0.1 for the 6.x line),

**Closed by richardlau** 2020-01-15 16:56 UTC
