### ISSUE TITLE
node-gyp build  error

### ISSUE THREAD

**Issue by 15313388469** [nodejs/node-gyp#923] opened 2016-05-10 06:24 UTC
when i was excuting "node-gyp build", i failed.all the way i follow the guidelines to handle the installtion, but it can't work,here are the error log(debug).i wish there is someone can fix this issue, and thanks all the time.
![e8d552e4-aabf-4840-8ca4-dbfaac4ec2cb](https://cloud.githubusercontent.com/assets/8520907/15137215/d3f6fae0-16ba-11e6-8ac1-055d84194bcf.png)

**Comment by bnoordhuis** [comment] 2016-05-10 07:52
It looks like you're executing node-gyp from the node-gyp directory itself?  You normally execute it from the directory that contains the add-on to build.

If it's not that, can you post steps to reproduce the issue?

**Comment by Spown** [comment] 2016-05-10 10:57
what if I installed it globally?

I also have build error. after updating to node.js 4.4.4 I ran ``npm update --gobal`` and got 3 pages of red text... well, nothing new, actually

**Comment by bnoordhuis** [comment] 2016-05-10 11:02
Then you still need to be in a directory containing an add-on.

By the way, I assume it's a typo in your comment but `--gobal` isn't a switch.

**Comment by Spown** [comment] 2016-05-10 11:03
yes, a typo

what addon? I just want to update all globally installed node_modules

**Comment by bnoordhuis** [comment] 2016-05-10 11:11
If you have issues with specific modules, please report them there.  Opening an issue here is only useful when you have a problem with node-gyp itself, not with the modules that you are trying to (re)build.

If you have reason to believe it's node-gyp, please provide more details than "got 3 pages of red text".  You're basically wasting my time when you're unspecific like that.

**Comment by karenpeng** [comment] 2016-05-15 20:10
I'm having a different error
```
> node-gyp rebuild

./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/shader-school/node_modules/canvas
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/usr/local/lib
└── (empty)
```

tried ```xcode-select --install``` as suggested by [this](https://github.com/Automattic/node-canvas/issues/722) but no use.

**Comment by bnoordhuis** [comment] 2016-05-15 20:14
@karenpeng

> ./util/has_lib.sh: line 30: pkg-config: command not found

That's an issue with the module you're trying to build (which looks to be... node-canvas?)

I'll close the issue now that I'm here, seeing the OP didn't follow up.

**Closed by bnoordhuis** 2016-05-15 20:14 UTC

**Comment by csaltos** [comment] 2019-06-30 12:22
In my case it does not work either, as in https://github.com/Automattic/node-canvas/issues/822 it's adviced to install couple of extra libraries and dependencies (this will cover pkg-config and others) ... but still not working ... that's very sad ... if someone find a real consistent way to do this, please let us know, thank you !!
