### ISSUE TITLE
Inability to build node-gyp on OSX affecting libui-node, create-proton-app

### ISSUE THREAD

**Issue by eyesno** [nodejs/node-gyp#1867] opened 2019-08-28 12:39 UTC
* **Node Version**: 12.9.0
* **Platform**: (OSX on Mac) Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
* **Compiler**: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
* **Module**: create-proton-app, also libgui-node by itself.

<details><summary>Installation of create-proton-app on Mac is failing seemingly due to a failure in libui-node which is failing on the build of node-gyp. The bug seems to be reported across multiple modules but as far as I can tell the issue here seems to be the root of it.</summary>

```
> libui-node@0.2.1 install /Users/darrylwright/projects/test/node_modules/libui-node
> libui-download && autogypi && npm run build

Downloaded zip: /Users/darrylwright/.libui/libui-shared-osx-x64-alpha3.5-master-008.tar.gz
Libui binaries extracted to: /Users/darrylwright/projects/test/node_modules/libui-node

> libui-node@0.2.1 build /Users/darrylwright/projects/test/node_modules/libui-node
> node-gyp configure build

  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/../nbind/src/common.o
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:139:8: warning: 'MarkIndependent' is deprecated: Weak objects are always considered independent. Use
      TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive. [-Wdeprecated-declarations]
                ref->MarkIndependent();
                     ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:563:3: note: 'MarkIndependent' has been explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:216:63: error: too few arguments to function call, single argument 'context' was not specified
                auto flags = static_cast<TypeFlags>(nanArgs[1]->Uint32Value());
                                                    ~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2580:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:217:38: error: expected '(' for function-style cast or type construction
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                       ~~~~~~~~~~~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: no member named 'Handle' in namespace 'v8'
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                            ~~~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:41: error: no member named 'Cast' in the global namespace
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                                    ~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: 'handle_' is a private member of 'node::ObjectWrap'
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/node_object_wrap.h:125:30: note: declared private here
  v8::Persistent<v8::Object> handle_;
                             ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:52:9: error: no matching member function for call to 'ToObject'
                        arg->ToObject(),
                        ~~~~~^~~~~~~~
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context',
      but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate',
      but no arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:96:9: error: no matching member function for call to 'ToObject'
                        arg->ToObject(),
                        ~~~~~^~~~~~~~
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context',
      but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate',
      but no arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:187:45: error: no matching member function for call to 'BooleanValue'
DEFINE_NATIVE_BINDING_TYPE(bool, IsBoolean, BooleanValue, v8::Boolean);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:33: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~^~~~~~
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2572:8: note: candidate function not viable: requires single argument 'isolate',
      but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2575:51: note: candidate function not viable: requires single argument 'context',
      but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:189:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(double, IsNumber, NumberValue, v8::Number);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2577:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:190:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(float, IsNumber, NumberValue, v8::Number);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2577:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:192:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned int, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2580:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:193:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned short, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2580:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:194:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned char, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2580:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:196:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(signed int, IsNumber, Int32Value, v8::Int32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2582:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:197:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(signed short, IsNumber, Int32Value, v8::Int32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2582:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:198:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(signed char, IsNumber, Int32Value, v8::Int32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2582:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:200:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(char, IsNumber, Int32Value, v8::Int32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2582:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:78:
../../nbind/include/nbind/v8/External.h:77:9: warning: 'MarkIndependent' is deprecated: Weak objects are always considered independent. Use TracedGlobal
      when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive. [-Wdeprecated-declarations]
                        weak.MarkIndependent();
                             ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:563:3: note: 'MarkIndependent' has been explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:78:
../../nbind/include/nbind/v8/External.h:112:71: error: no matching member function for call to 'ToObject'
        static inline Type fromWireType(WireType arg) { return(External(arg->ToObject())); }
                                                                        ~~~~~^~~~~~~~
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context',
      but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate',
      but no arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:80:
../../nbind/include/nbind/v8/BindingStd.h:128:28: error: no matching member function for call to 'ToString'
                Nan::Utf8String val(arg->ToString());
                                    ~~~~~^~~~~~~~
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2541:44: note: candidate function not viable: requires single argument 'context',
      but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/darrylwright/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2557:31: note: candidate function not viable: requires single argument 'isolate',
      but no arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make: *** [Release/obj.target/nbind/../nbind/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/darrylwright/projects/test/node_modules/libui-node
gyp ERR! node -v v12.9.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darrylwright/.npm/_logs/2019-08-28T12_18_54_717Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darrylwright/.npm/_logs/2019-08-28T12_18_55_152Z-debug.log
```
</details>

Log attached.
[2019-08-28T12_18_55_152Z-debug.log](https://github.com/nodejs/node-gyp/files/3550895/2019-08-28T12_18_55_152Z-debug.log)

**Comment by mpcarolin** [comment] 2019-09-10 02:04
I'm also encountering this.

**Comment by xpepermint** [comment] 2019-09-30 12:09
Ref https://github.com/nodejs/node-gyp/issues/1862

**Comment by bnoordhuis** [comment] 2019-11-03 09:05
Those build errors are caused by an outdated version of nan, not node-gyp. Not something node-gyp can fix, closing.

**Closed by bnoordhuis** 2019-11-03 09:05 UTC
Labels: macOS
