### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by aklkv** [nodejs/node-gyp#1231] opened 2017-06-14 20:50 UTC
Environment: 
Docker, docker-node latest

error:
```
> @newrelic/native-metrics@2.1.1 install /var/www/node_modules/@newrelic/native-metrics
 > node-gyp rebuild
 
 gyp info it worked if it ends with ok
 gyp info using node-gyp@3.6.2
 gyp info using node@8.1.1 | linux | x64
 gyp http GET https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
 gyp http 404 https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
 gyp WARN install got an error, rolling back install
 gyp ERR! configure error 
 gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
 gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
 gyp ERR! stack     at emitOne (events.js:120:20)
 gyp ERR! stack     at Request.emit (events.js:210:7)
 gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1074:10)
 gyp ERR! stack     at emitOne (events.js:115:13)
 gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
 gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
 gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
 gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
 gyp ERR! stack     at emitOne (events.js:115:13)
 gyp ERR! System Linux 4.9.27-moby
 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
 gyp ERR! cwd /var/www/node_modules/@newrelic/native-metrics
 gyp ERR! node -v v8.1.1
 gyp ERR! node-gyp -v v3.6.2
 gyp ERR! not ok 
 npm info lifecycle @newrelic/native-metrics@2.1.1~install: Failed to exec install script
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! @newrelic/native-metrics@2.1.1 install: `node-gyp rebuild`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the @newrelic/native-metrics@2.1.1 install script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2017-06-13T08_10_25_660Z-debug.log
```
Look like url is incorrect, according to nodejs.org, it should like something like this: `https://nodejs.org/dist/v8.1.1/node-v8.1.1-headers.tar.gz`

**Comment by gibfahn** [comment] 2017-06-14 21:15
Yep, this is a duplicate of https://github.com/nodejs/node/issues/13667 and https://github.com/nodejs/node-gyp/issues/1230.

I'll close this as a duplicate, it'll be fixed in the next Node 8 release. In the meantime you can use the workaround in https://github.com/nodejs/node/issues/13667.

**Closed by gibfahn** 2017-06-14 21:15 UTC
