### ISSUE TITLE
node-gyp rebuild issue

### ISSUE THREAD

**Issue by jitendrapawar** [nodejs/node-gyp#996] opened 2016-07-19 14:29 UTC
I am trying to install package "fabric", for which we need a canvas modules, for which we need to install node-gyp. But it gives error as below.
```
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at ChildProcess.spawn (child_process.js:1169:11)
gyp ERR! stack     at exports.spawn (child_process.js:999:9)
gyp ERR! stack     at exports.execFile (child_process.js:692:15)
gyp ERR! stack     at checkPythonVersion (/opt/node/lib/node_modules/npm/node_mo                                                                                                 dules/node-gyp/lib/configure.js:371:5)
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/c                                                                                                 onfigure.js:338:9
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/which.js                                                                                                 :79:20
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/node_mod                                                                                                 ules/isexe/index.js:44:5
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/node_mod                                                                                                 ules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bi                                                                                                 n/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/stage/nodejs/node_modules/fabric/node_modules/canvas
gyp ERR! node -v v0.12.15
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN optional dep failed, continuing canvas@1.4.0

> contextify@0.1.15 install /var/www/html/stage/nodejs/node_modules/fabric/node_                                                                                                 modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at ChildProcess.spawn (child_process.js:1169:11)
gyp ERR! stack     at exports.spawn (child_process.js:999:9)
gyp ERR! stack     at exports.execFile (child_process.js:692:15)
gyp ERR! stack     at checkPythonVersion (/opt/node/lib/node_modules/npm/node_mo                                                                                                 dules/node-gyp/lib/configure.js:371:5)
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/c                                                                                                 onfigure.js:338:9
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/which.js                                                                                                 :79:20
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/node_mod                                                                                                 ules/isexe/index.js:44:5
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/node_mod                                                                                                 ules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bi                                                                                                 n/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/stage/nodejs/node_modules/fabric/node_modules/jsdom/n                                                                                                 ode_modules/contextify
gyp ERR! node -v v0.12.15
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN optional dep failed, continuing jsdom@3.1.2
```

Please help me to resolve this...

**Comment by bnoordhuis** [comment] 2016-07-19 18:50
node-gyp is trying to spawn the python it found on your PATH but apparently it's not executable.  Possibly a permissions issue or maybe the python binary doesn't have the execute bit set.  Try passing `--python /path/to/python` to node-gyp or npm, where `/path/to/python` is a (working) python2.

**Comment by jitendrapawar** [comment] 2016-07-20 06:43
Thanks for your help. I corrected the path of python, but now it give another error as below.

`npm WARN package.json kreateapp@0.0.1 No repository field.
npm WARN package.json kreateapp@0.0.1 No README data

> canvas@1.4.0 install /var/www/html/stage/nodejs/node_modules/fabric/node_modul                                                                                                 es/canvas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/roo                                                                                                 t/.node-gyp/0.12.15"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/s                                                                                                 tage/nodejs/node_modules/fabric/node_modules/canvas/.node-gyp"
./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in bindin                                                                                                 g.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/node/lib/node_modules/npm/node                                                                                                 _modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078                                                                                                 :12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bi                                                                                                 n/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/stage/nodejs/node_modules/fabric/node_modules/canvas
gyp ERR! node -v v0.12.15
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional dep failed, continuing canvas@1.4.0

> contextify@0.1.15 install /var/www/html/stage/nodejs/node_modules/fabric/node_                                                                                                 modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/roo                                                                                                 t/.node-gyp/0.12.15"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/s                                                                                                 tage/nodejs/node_modules/fabric/node_modules/jsdom/node_modules/contextify/.node                                                                                                 -gyp"
`

As I checked the above path of .node-gyp folder, but there is no such(.node-gyp/0.12.15) folder.

**Comment by bnoordhuis** [comment] 2016-07-20 07:09
The real error is this:

> ./util/has_lib.sh: line 30: pkg-config: command not found

And that is not caused by node-gyp.  It looks like the build script for node-canvas shells out to pkg-config, which isn't on your path.

**Comment by jitendrapawar** [comment] 2016-07-20 08:43
Thanks for your help, it worked !!!

**Comment by bnoordhuis** [comment] 2016-07-20 09:11
Good to hear, I'll close the issue.

**Closed by bnoordhuis** 2016-07-20 09:11 UTC
