### ISSUE TITLE
Binary checksum different after each rebuild.

### ISSUE THREAD

**Issue by indieisaconcept** [nodejs/node-gyp#597] opened 2015-03-22 12:19 UTC
I've been trying to track down what would cause a rebuild to generate a binary with a different checksum. No files have changed and yet each time a rebuild is done it's different. 

I suspect a compile time timestamp or similar in being included within the result. 

Is anyone aware of an argument I can specify to prevent this behaviour?

**Comment by indieisaconcept** [comment] 2015-03-23 01:08
Further research has resulted in the possible use of the argument -frandom-seed=string. I'll give this a go - all going well I will close.

http://stackoverflow.com/questions/4140329/binary-object-file-changing-in-each-build

**Comment by indieisaconcept** [comment] 2015-03-23 12:07
I was hoping the following would work but seems to have no bearing on the output. It is included though as an argument.

```
  "xcode_settings": {
    ....
    "OTHER_CFLAGS":["-frandom-seed=0"]
    ....
  }
```

**Comment by rvagg** [comment] 2019-06-20 01:59
closing due to staleness, reproducable builds would be cool but I think there's a ton of work to do in the entire node toolchain, V8 possibly being the most difficult.

**Closed by rvagg** 2019-06-20 01:59 UTC

**Comment by Globegitter** [comment] 2019-06-28 19:27
@rvagg This also just came up today on a discussion around integration with Bazel (https://bazel.build/) which works with sha256 sums of binaries and actions for caching and incrementality. Running `yarn install` twice with the same `yarn.lock` does indeed create a binary with different checksums, which invalidates the cache but also in the end creates docker images with different checksums, also making them reuploaded etc, even if nothing as changed. I think it is worth keeping this open or at the very least link any issues from further down the node toolchan.

**Comment by Globegitter** [comment] 2019-06-28 19:32
Seems https://github.com/nodejs/build/issues/589 is related.

**Comment by refack** [comment] 2019-06-28 22:12
@Globegitter, do you have any leads as to where does the entropy come from? AFAICT `node-gyp` does create identical build files so it seems like the variability stems from the compiler/linked tools. Also did anyone happen to track this behavior across multiple platforms and compilers (Mac/Linux/Win X GCC/Clang/MSVC)?
