### ISSUE TITLE
404 response downloading node 8.1.1 headers

### ISSUE THREAD

**Issue by TheMetalCode** [nodejs/node-gyp#1232] opened 2017-06-14 21:57 UTC
I've started seeing this given a recent upgrade to node 8.1.1:

```
21:45:26 Output:
21:45:26 gyp info it worked if it ends with ok
21:45:26 gyp info using node-gyp@3.6.2
21:45:26 gyp info using node@8.1.1 | linux | x64
21:45:26 gyp http GET https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
21:45:26 gyp http 404 https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
21:45:26 gyp WARN install got an error, rolling back install
21:45:26 gyp ERR! configure error 
21:45:26 gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
```
The `download//` makes me concerned, as that url is almost certainly not correct. Question is - what is causing the URL to be formed that way?

**Comment by gibfahn** [comment] 2017-06-14 21:59
Yep, this is a duplicate of https://github.com/nodejs/node/issues/13667, https://github.com/nodejs/node-gyp/issues/1231 and https://github.com/nodejs/node-gyp/issues/1230.

I'll close this as a duplicate, it'll be fixed in the next Node 8 release. In the meantime you can use the workaround in https://github.com/nodejs/node/issues/13667.

**Closed** 2017-06-14 21:59 UTC
