### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by MLiranG** [nodejs/node-gyp#1517] opened 2018-07-31 15:43 UTC
* **Node Version**: node: 10.7.0 npm: 6.1.0
* **Platform**: Windows
* **Compiler**: 8136
* **Module**: errors with `npm i canvas-constructor` `npm i canvas-constructor` & node-gyp rebuild

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.7.0 | win32 | x64
gyp info spawn C:\Users\bargi\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\bargi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\bargi\\Desktop\\תכנות\\York-Dev\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\bargi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\bargi\\.node-gyp\\10.7.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\bargi\\.node-gyp\\10.7.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\bargi\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\bargi\\.node-gyp\\10.7.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\bargi\\Desktop\\תכנות\\York-Dev',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\bargi\\Desktop\\תכנות\\York-Dev\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\register_font.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\color.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\toBuffer.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\Canvas.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\CanvasRenderingContext2d.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\Backends.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\init.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\backend\ImageBackend.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\CanvasPattern.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\ImageData.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\Image.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\backend\SvgBackend.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\CanvasGradient.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\backend\Backend.cc
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\closure.cc
C:\libjpeg-turbo-gcc\bin\jpeg62.dll
C:\Users\bargi\Desktop\·δ≡σ·\York-Dev\build\..\src\backend\PdfBackend.cc
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:/libjpeg-turbo-gcc/bin/jpeg62.dll to C:\Users\bargi\Desktop\תכנות\York-Dev\build\Release\\jpeg62.dll
  The system cannot find the file specified.
  Backend.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\backend\Backend.cc': No such file or directory [C:\Users\
bargi\Desktop\תכנות\York-Dev\build\canvas.vcxproj]
  ImageBackend.cc
  PdfBackend.cc
  SvgBackend.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\backend\ImageBackend.cc': No such file or directory [C:\U
sers\bargi\Desktop\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\backend\PdfBackend.cc': No such file or directory [C:\Use
rs\bargi\Desktop\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\backend\SvgBackend.cc': No such file or directory [C:\Use
rs\bargi\Desktop\תכנות\York-Dev\build\canvas.vcxproj]
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\CanvasGradient.cc': No such file or directory [C:\Users\b
argi\Desktop\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\Backends.cc': No such file or directory [C:\Users\bargi\D
esktop\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\CanvasPattern.cc': No such file or directory [C:\Users\ba
rgi\Desktop\תכנות\York-Dev\build\canvas.vcxproj]
  CanvasRenderingContext2d.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\Canvas.cc': No such file or directory [C:\Users\bargi\Des
ktop\תכנות\York-Dev\build\canvas.vcxproj]
  closure.cc
  color.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\closure.cc': No such file or directory [C:\Users\bargi\De
sktop\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\CanvasRenderingContext2d.cc': No such file or directory [
C:\Users\bargi\Desktop\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\color.cc': No such file or directory [C:\Users\bargi\Desk
top\תכנות\York-Dev\build\canvas.vcxproj]
  Image.cc
  ImageData.cc
  init.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\ImageData.cc': No such file or directory [C:\Users\bargi\
Desktop\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\Image.cc': No such file or directory [C:\Users\bargi\Desk
top\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\init.cc': No such file or directory [C:\Users\bargi\Deskt
op\תכנות\York-Dev\build\canvas.vcxproj]
  register_font.cc
  toBuffer.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\register_font.cc': No such file or directory [C:\Users\ba
rgi\Desktop\תכנות\York-Dev\build\canvas.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\toBuffer.cc': No such file or directory [C:\Users\bargi\D
esktop\תכנות\York-Dev\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\bargi\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bargi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bargi\Desktop\תכנות\York-Dev
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

</details>

**Comment by joaocgreis** [comment] 2018-08-02 03:51
@MLiranG `npm i canvas-constructor` works fine in my machine. From your output, it looks like you are running node-gyp on a project you are developing. I see warnings that some `*.cc` files are missing, you should either ensure they exist or remove them from your `binding.gyp`.

This repository is for issues with node-gyp itself, not issues using it. https://github.com/nodejs/help might be a better place to report this.

**Comment by maclover7** [comment] 2018-08-14 15:49
Agree with @joaocgreis, issue seems to lie with project, not a bug in node-gyp. Closing for now, please reopen if I'm mistaken.

**Closed by maclover7** 2018-08-14 15:49 UTC
