### ISSUE TITLE
node-gyp-build error with yarn add, MacOS Xcode libtool can`t open file

### ISSUE THREAD

**Issue by zuoning777** [nodejs/node-gyp#2459] opened 2021-07-22 03:05 UTC
* **Node Version**: 14.17.3
* **Platform**: MacOs Big Sur 11.4
* **Compiler**: 
* **Module**: ffi-napi

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
> yarn add
...
error /Users/xxx/Desktop/react-demo/node_modules/ffi-napi: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /Users/xxx/Desktop/react-demo/node_modules/ffi-napi
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@14.17.3 | darwin | x64
gyp info find Python using Python version 3.9.6 found at "/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9"
gyp info spawn /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/xxx/.nvm/versions/node/v14.17.3/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xxx/Desktop/react-demo/node_modules/ffi-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xxx/.nvm/versions/node/v14.17.3/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xxx/Library/Caches/node-gyp/14.17.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/xxx/Library/Caches/node-gyp/14.17.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/xxx/.nvm/versions/node/v14.17.3/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/xxx/Library/Caches/node-gyp/14.17.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/xxx/Desktop/react-demo/node_modules/ffi-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
0.1.2
  LIBTOOL-STATIC Release/nothing.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: Release/obj.target/nothing/../node-addon-api/src/nothing.o (No such file or directory)
make: *** [Release/nothing.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.nvm/versions/node/v14.17.3/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/Users/xxx/.nvm/versions/node/v14.17.3/bin/node" "/Users/xxx/.nvm/versions/node/v14.17.3/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/Desktop/react-demo/node_modules/ffi-napi
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v8.1.0
gyp ERR! not ok
```

**Comment by zuoning777** [comment] 2021-07-28 09:09
emmmm:(

**Comment by asnawisaharuddin** [comment] 2021-09-07 07:43
I have the same issue

**Comment by lizengjia** [comment] 2022-09-19 07:59
I solved this problem by using npm i  .    not  yarn add

**Comment by cclauss** [comment] 2024-08-27 08:13
https://github.com/nodejs/node-gyp/labels/ffi-napi

Duplicate of
* node-ffi-napi/node-ffi-napi#269

**Closed by cclauss** 2024-08-27 08:13 UTC
Labels: macOS, ffi-napi
