### ISSUE TITLE
npm link pg command produced errors that says to please file a bug

### ISSUE THREAD

**Issue by kishore104** [nodejs/node-gyp#352] opened 2013-11-13 20:23 UTC
Running npm link pg command produces endless error with these type of error messages:

gyp ERR! System Linux 2.6.32-358.18.1.el6.x86_64
gyp ERR! command "node" "/x/opt/pp/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /x/opt/pp/lib/node_modules/pg
gyp ERR! node -v v0.10.4
gyp ERR! node-gyp -v v0.9.5
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     https://github.com/TooTallNate/node-gyp/issues

**Comment by philj0** [comment] 2018-03-13 14:02
Is this bug still exist? I would suggestion to close this issue, because there was no input to reproduce the bug.

**Comment by gibfahn** [comment] 2018-03-14 13:20
I think if this is still an issue it's probably worth raising a new issue at this point.

**Closed by gibfahn** 2018-03-14 13:20 UTC
Labels: Linux, Waiting For Input
