### ISSUE TITLE
Linking framework to an addon

### ISSUE THREAD

**Issue by gerhardberger** [nodejs/node-gyp#682] opened 2015-08-05 12:34 UTC
hi

i'm having trouble using a framework in my addon.
i have framework called `Foo.framework` and i can't figure out how to describe it in `binding.gyp`. if i put it into the `/Library/Frameworks` folder and in `binding.gyp` i write:

``` gyp
{
  'libraries': [ '-framework Foo' ]
}
```

it works, but i don't want to put it in a global folder.
if i write my `binding.gyp` like this:

``` gyp
{
  'libraries': [ '-F/path/to/frameworks -framework Foo' ]
}
```

it builds the addon successfully, but when i run the program i get:

``` bash
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/gerhard/Desktop/project/build/Release/example.node, 1):
Library not loaded: @executable_path/../Frameworks/Foo.framework/Versions/1.10.0/Foo
  Referenced from: /Users/gerhard/Desktop/project/build/Release/example.node
  Reason: image not found
    at Error (native)
```

i tried to put a `Frameworks` folder with the framework next to the addon but it didn't work and i can't figure out what the value of `@executable_path` is or how can i override it.

thanks

**Comment by saw666** [comment] 2017-04-17 10:12
Hi,

Did you ever manage to make this work? I'm having the same issue and I'm stuck... 

Thanks!

**Comment by mortengf** [comment] 2017-06-09 09:36
I have the same issue trying to use a Qt 5.8 framework, e.g. `QtCore`, in my native node application (broke after upgrading to Qt 5.8). This uses `@rpath` (not `@executable_path`), though, but it is probably the same issue (and solution) as mentioned above.

I admit I am a newbie to C++ dynamic linking (frameworks on Mac) but I have read a lot of documentation/SO posts on e.g. `node-gyp`, `@rpath` and `qmake` and tried a lot of different things.

Using absolute paths via `install_name_tool -id`...

```
install_name_tool -id /Users/skyfer/Qt5.8/5.8/clang_64/lib/QtCore.framework/QtCore QtCore.framework/QtCore
```

(`cwd` == /Users/skyfer/Qt5.8/5.8/clang_64/lib)

...and setting `libraries` in `binding.gyp` to...

```
'-F<!@(qmake -query "QT_INSTALL_PREFIX")/lib',
'-framework QtCore',
'-framework ...',
```

...solves the immediate problem but "pushes the problem back" to one of `QtWebKit`'s "rpath dependencies"...

```
[Error: dlopen(/Users/skyfer/git/CloudScrape/node/browser_engines/src/browsers/webkit/build/Debug/nodekit.node, 1): Library not loaded: @rpath/QtPositioning.framework/Versions/5/QtPositioning
  Referenced from: /Users/skyfer/Qt5.8/5.8/clang_64/lib/QtWebKit.framework/QtWebKit
  Reason: image not found]
```

...meaning that this might not be the way to go.

Some basic questions:

1. Does [OS X' `dlopen()`](http://www.manpages.info/macosx/dlopen.3.html) (or any other utility) understand `@rpath`s (in object, e.g. `.node`, files)?
1. If not, what is the correct way of resolving such paths into "real" paths (at build time)?

**Comment by bnoordhuis** [comment] 2017-06-12 13:58
You can probably make it work if you add `'-Wl,-rpath,<!@(qmake -query "QT_INSTALL_PREFIX")/lib'` to the link flags.

**Comment by mortengf** [comment] 2017-06-12 15:32
Using your suggestion *and* `-framework <name>` in `link_settings` worked! (so yes, `dlopen()` understands `@rpath`)

Thank you so much!

**Comment by edin-m** [comment] 2017-09-22 23:40
@mortengf Can you share entire binding.gyp? I'm having trouble with include dirs.

**Comment by mortengf** [comment] 2017-09-23 11:03
@edin-m Unfortunately I am not allowed to share the entire file but I can copy-paste an example of the contents of the `include_dirs`, `link_settings` and `libraries` sections which were causing me headaches:

```
'include_dirs': [
	'<!@(qmake -query "QT_INSTALL_PREFIX")/include',
	'<!@(qmake -query "QT_INSTALL_PREFIX")/include/QtCore',
	...
],
'link_settings': {
	'libraries': [
		'-Wl,-rpath,<!@(qmake -query "QT_INSTALL_PREFIX")/lib',
		'-framework QtCore',
		...
	],
},
'libraries': [
	'-F<!@(qmake -query "QT_INSTALL_PREFIX")/lib',
	'-framework QtCore',
	...
]
```

I hope it helps you.

**Comment by edin-m** [comment] 2017-09-23 17:13
Thanks, @mortengf. It helps a bit. My problem is that - maybe it's just my mac - but there is no QtCore in /includes in Qt dir. Headers are inside QtCore.framework/Headers but that doesn't help since (for example) QPoint does #include <QtCore/qpoint.h> so included dirs should be able to find QPoint and QtCore/qpoint.h. It's a hassle with `.framework` package.

It's not exactly related to this thread but any help is welcome.

If I set the paths manually just to compile, when loading I get `Incompatible library version: hello.node requires version 5.8.0 or later, but QtCore provides version 5.3.0` which is something I'm working on now.

**Comment by mortengf** [comment] 2017-09-23 20:39
@edin-m It seems that QtCore is installed very oddly (buggy) on Mac in certain versions of Qt, e.g. 5.8 or 5.9. I had to do a fix like:

```
ln -s $HOME/Qt5.9/5.9/clang_64/lib/QtCore.framework/Headers/5.9.0/QtCore/private/ $HOME/Qt5.9/5.9/clang_64/lib/QtCore.framework/Headers/private
```

**Comment by maclover7** [comment] 2018-07-20 18:57
Seems like the issue is with Qt now, not with node-gyp, so going to close this out.

**Closed by maclover7** 2018-07-20 18:57 UTC
