### ISSUE TITLE
Convert to Python 3

### ISSUE THREAD

**Issue by tigerhawkvok** [nodejs/node-gyp#737] opened 2015-09-20 17:41 UTC
Yikes! This was a shocker. I'd expect this back in 2012, but not on the tail end of 2015.

Proposed paths:

- Since this uses the Chromium dependency Gyp, which is no longer actively maintained by Google ([who ignores this issue](https://code.google.com/p/gyp/issues/detail?id=36), migrate the back-end to [GN, which is supported](https://chromium.googlesource.com/chromium/src/+/master/tools/gn/README.md)  **probably least ideal** 
- Work with a [python 3 compatible port, like this](https://github.com/saghul/gyn)
- Manually port Gyp as part of the greater nodejs environment (thus becoming the active maintainer). **Probably most ideal**

Why?

- [It's good practice](https://docs.python.org/3/howto/pyporting.html)
- Python 3, [released in 2008](https://wiki.python.org/moin/Python2orPython3), is officially older than the [amount of time Python2 has remaining](https://hg.python.org/peps/rev/76d43e52d978) -- which is now just a touch over 4 years. (And, let's be honest -- if you're butting up against the EOL, without at least a year for dependencies to get their stuff in line, you're doing it wrong).
- Most major projects are Python 3 compatible nowadays -- this makes `node-gyp` That Legacy Project We Have To Support

**Comment by thefourtheye** [comment] 2015-09-20 17:51
I would love to help with Python-3 compatibility, if decided to do so.

**Comment by rvagg** [comment] 2015-09-21 12:47
Yeah, maybe a good idea, would make life easier for a lot of people. I have [prior-art](https://github.com/rvagg/node-pygmentize-bundled/blob/master/index.js#L123-L141) for switching based on Python versions, my main concern here is that since we'd be using a fork for people that have v3 installed there would be disparity between the code being executed, not just the runtime used (unless the v3 fork of gyp can be used with v2?).

The alternative path is a wholesale upgrade, including Node core, and moving to v3 being required, but that would be really painful and we may face bigger barriers getting a gyp fork into core.

**Comment by mangecoeur** [comment] 2015-11-07 19:44
lack of python3 is a huge pain, and only going to get worse as distros like Fedora and Ubuntu default to python3. What needs to happen for this to happen?

**Comment by bnoordhuis** [comment] 2015-11-08 11:39
Upstream gyp would have to convert to python 3, which is unlikely to happen if this 6 year old bug report is anything to go by: https://bugs.chromium.org/p/gyp/issues/detail?id=36

I'll close the issue, it's a duplicate of #193.

**Closed by bnoordhuis** 2015-11-08 11:39 UTC

**Comment by bnoordhuis** [comment] 2015-11-08 11:42
> Work with a [python 3 compatible port, like this](https://github.com/saghul/gyn)

For posterity, I think this is a good idea in general but the devil is in the details.  gyp files have a lot of python code in them that is executed verbatim (as python 2 code obviously.)
