### ISSUE TITLE
node-pre-gyp ERR! build error 

### ISSUE THREAD

**Issue by tomkimsour** [nodejs/node-gyp#2164] opened 2020-07-07 08:12 UTC
* **Node Version**:  
`node` : v14.5.0 and `npm -v`:6.14.5
* **Platform**: 
Linux raspberrypi 4.19.118+ #1311 Mon Apr 27 14:16:15 BST 2020 armv6l GNU/Linux
* **Compiler**: 
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)

* **Module**: 
I am trying to install Sqlite3 on a raspberry pi zero which works on armv6. By using this command `npm install sqlite3 --save`, I get this output.

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
> sqlite3@4.2.0 install /home/pi/Smartvac/SmartVacAppV3.1/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-arm
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.5.0 (node-v83 ABI, glibc) (falling back to
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: tar.extract is not a function
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:199:22)
gyp ERR! stack     at Request.emit (events.js:326:22)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1066:1
gyp ERR! stack     at ClientRequest.emit (events.js:314:20)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:509:22)
gyp ERR! stack     at TLSSocket.emit (events.js:314:20)
gyp ERR! stack     at addChunk (_stream_readable.js:304:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:280:9)
gyp ERR! System Linux 4.19.118+
gyp ERR! command "/opt/nodejs/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "config-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/pi/Smartvac/SmartVacAppV3.1/node_modules/sqlibel=node-v83"
gyp ERR! cwd /home/pi/Smartvac/SmartVacAppV3.1/node_modules/sqlite3
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/opt/nodejs/bin/node /usr/local/lib/node_modules/npm/node_modules/nodb/binding/node-v83-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/Smartvac/SmartVacAppV3node_napi_label=node-v83' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/Smartvac/SmartVacAppV3.1/node_modules/node-pre-gyp/li
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.19.118+
node-pre-gyp ERR! command "/opt/nodejs/bin/node" "/home/pi/Smartvac/SmartVacAppV3.1/node_modules/.bin/node-pre-gyp" "in
node-pre-gyp ERR! cwd /home/pi/Smartvac/SmartVacAppV3.1/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/opt/nodejs/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configurede_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/Smartvac/SmartVacAppV3.1/node_modules/sqlite3/lib/bin
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"an

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-07T07_43_04_068Z-debug.log

```

</details>

**Comment by cclauss** [comment] 2020-07-07 08:35
https://github.com/nodejs/node-gyp/search?q=TypeError%3A+tar.extract+is+not+a+function&type=Issues

**Comment by tomkimsour** [comment] 2020-07-07 08:42
> 
> 
> https://github.com/nodejs/node-gyp/search?q=TypeError%3A+tar.extract+is+not+a+function&type=Issues
> Esp. [#2067 (comment)](https://github.com/nodejs/node-gyp/issues/2067#issuecomment-597362973)
> 
> > node-gyp ERR! node-gyp -v v5.1.0
> > node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> 
> Current versions are v7 and v0.15.0.

How am I supposed to change that ?

**Comment by rvagg** [comment] 2020-07-08 06:19
@tomkimsour the first thing to try is probably just reinstalling your npm - clean out the old one as completely as you can. This error seems to always be associated with a bad install of a newer npm over an older one. Remove it all and start again. On Linux the most important thing to remove is either /usr/lib/node_modules/npm or /usr/local/lib/node_modules/npm, whichever exists (or maybe your global node_modules is elsewhere). Just manually delete it. Then reinstall Node.

Ideally you could upgrade node-gyp but it's complicated. Get Node reinstalled and working and maybe that'll solve this particular problem alone.

**Comment by tomkimsour** [comment] 2020-07-08 08:15
> 
> 
> @tomkimsour the first thing to try is probably just reinstalling your npm - clean out the old one as completely as you can. This error seems to always be associated with a bad install of a newer npm over an older one. Remove it all and start again. On Linux the most important thing to remove is either /usr/lib/node_modules/npm or /usr/local/lib/node_modules/npm, whichever exists (or maybe your global node_modules is elsewhere). Just manually delete it. Then reinstall Node.
> 
> Ideally you could upgrade node-gyp but it's complicated. Get Node reinstalled and working and maybe that'll solve this particular problem alone.

@rvagg i did it and also reinstalled the entire os the same problem keeps occuring.

**Comment by tomkimsour** [comment] 2020-07-10 06:44
@rvagg any other clue on how to solve the problem here ? Btw could you please reopen the issue

**Comment by cclauss** [comment] 2020-07-10 06:56
Does your log still contain:
* node-gyp ERR! node-gyp -v v5.1.0
* node-pre-gyp ERR! node-pre-gyp -v v0.11.0

**Comment by rvagg** [comment] 2020-07-11 00:45
@tomkimsour `TypeError: tar.extract is not a function` was never an error that occurred here, it's not a bug we've had to fix. It showed up at some point I think during npm v5 or some older iteration where they refactored where things were located within their node_modules and then an install of a newer version didn't properly wipe out the old version and we had an unresolved dependency, or a badly resolved dependency.

I'm 99% certain this bug is related to bad installs on your system, or packages getting mixed up due to module resolution bringing in things it shouldn't. I don't know what else to give you on this, it's not something we can fix here, you need to hunt it down on your system, wherever Node may be resolving packages, and clean stuff out.

**Comment by cclauss** [comment] 2020-07-11 04:57
[4 other issues with `tar.extract is not a function `](https://github.com/nodejs/node-gyp/search?q=TypeError%3A+tar.extract+is+not+a+function&type=Issues)

**Comment by rvagg** [comment] 2020-07-11 05:09
^ but none of those are actionable by us. It's because the `tar` dependency got shuffled around and it left npm and node-gyp in an inconsistent state when an npm upgrade didn't properly remove old versions. Unless someone can show how this is our problem, there's zero we can do about it. Use node-gyp independently if you can't solve it, or go complain to npm but you'll probably get the same answer because I bet their bug tracker is full of the same thing.

**Comment by DeeDeeG** [comment] 2020-07-18 18:59
> TypeError: tar.extract is not a function

The `tar` module updated its api in its major version bump to v3.
https://github.com/npm/node-tar/blob/master/CHANGELOG.md#30

The correct function when depending on `tar@3` or newer is not `tar.extract()`, but `tar.x()`.

The code depending on `tar` should be updated to reflect that.

**Closed** 2020-09-21 13:10 UTC
