### ISSUE TITLE
npm install fail on windows

### ISSUE THREAD

**Issue by sujanmah062** [nodejs/node-gyp#2086] opened 2020-04-02 04:32 UTC
![error](https://user-images.githubusercontent.com/25734794/78210863-2b307300-74cb-11ea-869e-bc931560cd8d.PNG)

**Comment by cclauss** [comment] 2020-04-02 06:10
Node-gyp 3.0.8 should v5 or v6

**Comment by bzoz** [comment] 2020-04-02 06:43
Besides updating node-gyp to never version, please also provide the entire verbose log, including the command you are running and the thing you are trying to compile. Your OS and compiler versions are also important. The issue template is there for a reason.

**Comment by Adelelele** [comment] 2020-04-02 08:27
i have same error with node-gyp v6 :/
![Bez tytułu](https://user-images.githubusercontent.com/63041828/78226429-fc66cc80-74cb-11ea-8fb4-2ade8f946ad7.png)
[2020-04-02T08_25_26_443Z-debug.log](https://github.com/nodejs/node-gyp/files/4419704/2020-04-02T08_25_26_443Z-debug.log)

**Comment by cclauss** [comment] 2020-04-02 08:37
That repo has not been touched in 4 years and there are several open issues that saying it is broken but perhaps node-mariasql/issues#207 sums things up the best.

**Comment by Adelelele** [comment] 2020-04-02 09:02
it didnt help. i think its not maria fault

![Bez tytułu](https://user-images.githubusercontent.com/63041828/78230333-79487500-74d1-11ea-9c46-e1878a50490a.png)
[2020-04-02T08_57_04_080Z-debug.log](https://github.com/nodejs/node-gyp/files/4419899/2020-04-02T08_57_04_080Z-debug.log)

**Comment by bzoz** [comment] 2020-04-02 09:08
It says it cannot find the msbuild executable. I see the path to msbuild uses localized "Pliki programów" instead of  the general "Program files". Could you check if the msbuild executable is really in that folder?

**Comment by Adelelele** [comment] 2020-04-02 09:21
it is. this command says its found
![Bez tytułu1](https://user-images.githubusercontent.com/63041828/78232092-0d1b4080-74d4-11ea-9e3a-aa8927ae1e1d.png)

**Comment by bzoz** [comment] 2020-04-02 09:36
@Adelelele the command will query the installer for the installed VS versions and workloads, I'm not sure if it checks if the file is really there. Could you verify in File Explorer that the file is present on disk?

Generally, node-gyp does not like non-ascii chars in path, so that "programów" could be the issue. I also run polish Windows10, but I have VS in "Program Files". Changing the VS language also does not change that.

Anyway, mariasql is broken and will not compile. Still, the compilation should fail, not running the toolchain.

Oh, and please paste the text from the console, not screenshots. Do this like this (new lines are important):
<pre>
```
C:\Users\ja\Desktop\Work\test>npm install --save --verbose mariasql
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Users\\ja\\AppData\\Local\\nvs\\node\\12.16.1\\x64\\node.exe',
npm verb cli   'C:\\Users\\ja\\AppData\\Local\\nvs\\node\\12.16.1\\x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--save',
npm verb cli   '--verbose',
npm verb cli   'mariasql'
npm verb cli ]
npm info using npm@6.13.4
npm info using node@v12.16.1
npm verb npm-session 2ee4474edaba1251
npm http fetch GET 200 https://registry.npmjs.org/mariasql 13ms (from cache)
npm timing stage:loadCurrentTree Completed in 44ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm http fetch GET 304 https://registry.npmjs.org/lru-cache 319ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 321ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 330ms
npm timing stage:loadIdealTree Completed in 335ms
npm timing stage:generateActionsToTake Completed in 4ms
(...)
```
</pre>

**Comment by bzoz** [comment] 2020-04-02 09:38
Could you also try switching VS to English? In the installer use "modyfikuj" and select those:
![image](https://user-images.githubusercontent.com/17704638/78233726-7603b800-74d6-11ea-8532-76de1b63c2d6.png)

**Comment by bzoz** [comment] 2020-04-02 09:49
Could you also run in CMD:
```
"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
```
and paste its output here

**Comment by Adelelele** [comment] 2020-04-02 10:25
Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: d050ab5c
installDate: 11.05.2019 13:16:08
installationName: VisualStudio/16.5.2+29926.136
installationPath: C:\Pliki programów\Visual Studio
installationVersion: 16.5.29926.136
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Pliki programów\Visual Studio\Common7\IDE\devenv.exe
state: 4294967295
isComplete: 1
isLaunchable: 1
isPrerelease: 0
isRebootRequired: 0
displayName: Visual Studio Community 2019
description: Zaawansowane środowisko IDE — bezpłatne dla uczniów i studentów, współautorów oprogramowania open source oraz indywidualnych osób
channelId: VisualStudio.16.Release
channelUri: https://aka.ms/vs/16/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660893#16.5.2
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660909
updateDate: 2020-04-01T18:36:47.7360612Z
catalog_buildBranch: d16.5
catalog_buildVersion: 16.5.29926.136
catalog_id: VisualStudio/16.5.2+29926.136
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 16.5.2
catalog_productLine: Dev16
catalog_productLineVersion: 2019
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 2
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productSemanticVersion: 16.5.2+29926.136
catalog_requiredEngineVersion: 2.5.2139.10695
properties_campaignId: 130484628.1556359399
properties_channelManifestId: VisualStudio.16.Release/16.5.2+29926.136
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe

**Comment by Adelelele** [comment] 2020-04-02 10:26
i'll move studio to "Program files"

**Comment by bzoz** [comment] 2020-04-02 10:52
Hm, I have my vs also in pliki programów because that's just localized program files folder name. But vswhere reports program files path.

I see you might have newer version, I'll try updating and reproducing this.

**Comment by Adelelele** [comment] 2020-04-02 11:41
i switched to mariaDb and it works.
Thanks for help

**Comment by cclauss** [comment] 2020-04-02 11:48
Close this issue?

**Comment by Adelelele** [comment] 2020-04-02 11:55
Ya. thanks

**Comment by bzoz** [comment] 2020-04-02 12:06
The issue was open by @sujanmah062, their issue could be different from @Adelelele one

**Comment by bnoordhuis** [comment] 2020-04-28 13:22
OP never followed up so I'm closing this.

**Closed by bnoordhuis** 2020-04-28 13:22 UTC
