### ISSUE TITLE
when i am installing bcrypt with npm node-gyp rebuild is showing errors

### ISSUE THREAD

**Issue by cs12b015** [nodejs/node-gyp#651] opened 2015-06-25 15:08 UTC
I am trying to install the bcrypt with npm in my app in which node version is v0.10.25 and npm version is 2.11.1. and node-gyp version is v2.0.1 . i am encountering this error could you help me with this. Thanks in advance
> jayanth@DeViLsOwN:~/Documents/rupeek-web/app$ npm install bcrypt |
> bcrypt@0.8.3 install /home/jayanth/Documents/rupeek-web/app/node_modules/bcrypt node-gyp rebuild
> Usage: gyp_main.py [options ...] [build_file ...]

```
gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-49-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jayanth/Documents/rupeek-web/app/node_modules/bcrypt
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-49-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "bcrypt"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jayanth/Documents/rupeek-web/app/npm-debug.log
```

**Comment by Fishrock123** [comment] 2015-08-23 16:42
dupe of https://github.com/nodejs/node-gyp/issues/655

**Closed by Fishrock123** 2015-08-23 16:42 UTC
Labels: duplicate
