### ISSUE TITLE
npm configuration cause node-gyp failed to compile addon modules

### ISSUE THREAD

**Issue by bruceauyeung** [nodejs/node-gyp#2062] opened 2020-03-07 12:06 UTC
* **Node Version**: 
 `node -v`: v12.8.1
`npm -v`: 6.10.2

* **Platform**: 
>\>systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"
>OS Name:                   Microsoft Windows 7 ???
>OS Version:                6.1.7601 Service Pack 1 Build 7601
>System Type:               x64-based PC

* **Compiler**: 
vs 2017 community

>\>msbuild /version & cl
>Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
>Copyright (C) Microsoft Corporation. All rights reserved.
>
>15.9.21.664?? x64 ? Microsoft (R) C/C++ ????? 19.16.27035 ?
>????(C) Microsoft Corporation????????
>??: cl [ ??... ] ???... [ /link ????... ]
* **Module**: ffi-napi, ref-napi

`npm config set ELECTRON_MIRROR "https://npm.taobao.org/mirrors/electron/"` caused node-gyp failed to compile addon modules, more specifically, caused `Find-VisualStudio.cs` failed to find Visual Studio 2017

<details><summary>Verbose output (from npm or node-gyp):</summary>
if i run `npm config set ELECTRON_MIRROR "https://npm.taobao.org/mirrors/electron/"` before `yarn install`, error occurs:

>gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer

at the beginning,  i haven't any clue to find out what clause the problem. i tried to reinstall / repair visual studio 2017 community, to install visual studio 2019 community and set `msvs_version=2019`, but all these doesn't work out.

i add some logs in `failPowershell` function in `C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js` to get more detailed logs, these logs help me find out the cause. the following is what i added:

>  parseData: function parseData (err, stdout, stderr, cb) {
>    this.log.error('PS stderr = %j', stderr)
>    const failPowershell = () => {
>      this.addLog(
>        'could not use PowerShell to find Visual Studio 2017 or newer')
>      this.addLog(`------err:${err}`)   -- what i added
>	  this.addLog(`------stderr:${stderr}`)	-- what i added  
>      cb(null)
>    }

# here the logs come:

>D:\Home\icenter-next>npm config set ELECTRON_MIRROR "https://npm.taobao.org/mirrors/electron/"
>
>D:\Home\icenter-next>yarn install
>yarn install v1.22.0
>[1/4] Resolving packages...
>success Already up-to-date.
>$ electron-builder install-app-deps && node hooks/fix_electron_installation.js
>   electron-builder  version=22.3.2
>   rebuilding native dependencies  dependencies=ffi-napi@2.4.6, ref-napi@1.4.3 platform=win32 arch=ia32
>   rebuilding native dependency  name=ffi-napi version=2.4.6
>   rebuilding native dependency  name=ref-napi version=1.4.3
>  ? cannot execute  cause=exit status 1
>                    out=yarn run v1.22.0
>    $ node-gyp rebuild
>
>    D:\Home\icenter-next\node_modules\ref-napi>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\
>node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
>    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>
>    errorOut=gyp info it worked if it ends with ok
>    gyp info using node-gyp@5.0.3
>    gyp info using node@12.8.1 | win32 | ia32
>    gyp info find Python using Python version 2.7.17 found at "C:\Python27\python.exe"
>    gyp ERR! find VS PS stderr = "Add-Type : Item has already been added. Key in dictionary: 'npm_config_electron_mirror'  Key being added: 'npm_config_electron
>_mirror'\r\nAt line:1 char:11\r\n+ &{Add-Type <<<<  -Path 'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\Find-VisualStudio.cs
>';[VisualStudioConfiguration.Main]::Prin\r\ntJson()}\r\n    + CategoryInfo          : NotSpecified: (:) [Add-Type], ArgumentException\r\n    + FullyQualifiedErr
>orId : System.ArgumentException,Microsoft.PowerShell.Commands.AddTypeCommand\r\n \r\nUnable to find type [VisualStudioConfiguration.Main]: make sure that the as
>sembly containing this type is loaded.\r\nAt line:1 char:146\r\n+ &{Add-Type -Path 'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\
>lib\\Find-VisualStudio.cs';[VisualStudioConfiguration.Main] <<<< ::Prin\r\ntJson()}\r\n    + CategoryInfo          : InvalidOperation: (VisualStudioConfiguratio
>n.Main:String) [], RuntimeException\r\n    + FullyQualifiedErrorId : TypeNotFound\r\n \r\n"
>    gyp ERR! find VS
>    gyp ERR! find VS msvs_version was set from command line or npm config
>    gyp ERR! find VS - looking for Visual Studio version 2017
>    gyp ERR! find VS running in VS Command Prompt, installation path is:
>    gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
>    gyp ERR! find VS - will only use this version
>    gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
>    gyp ERR! find VS ------err:null
>    gyp ERR! find VS ------stderr:Add-Type : Item has already been added. Key in dictionary: 'npm_config_electron_mirror'  Key being added: 'npm_config_electron
>_mirror'
>    gyp ERR! find VS At line:1 char:11
>    gyp ERR! find VS + &{Add-Type <<<<  -Path 'C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\Find-VisualStudio.cs';[VisualStudioConfi
>guration.Main]::Prin
>    gyp ERR! find VS tJson()}
>    gyp ERR! find VS     + CategoryInfo          : NotSpecified: (:) [Add-Type], ArgumentException
>    gyp ERR! find VS     + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.AddTypeCommand
>    gyp ERR! find VS
>    gyp ERR! find VS Unable to find type [VisualStudioConfiguration.Main]: make sure that the assembly containing this type is loaded.
>    gyp ERR! find VS At line:1 char:146
>    gyp ERR! find VS + &{Add-Type -Path 'C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\Find-VisualStudio.cs';[VisualStudioConfigurati
>on.Main] <<<< ::Prin
>    gyp ERR! find VS tJson()}
>    gyp ERR! find VS     + CategoryInfo          : InvalidOperation: (VisualStudioConfiguration.Main:String) [], RuntimeException
>    gyp ERR! find VS     + FullyQualifiedErrorId : TypeNotFound
>    gyp ERR! find VS
>    gyp ERR! find VS
>    gyp ERR! find VS looking for Visual Studio 2015
>    gyp ERR! find VS - not found
>    gyp ERR! find VS looking for Visual Studio 2013
>    gyp ERR! find VS - not found
>    gyp ERR! find VS msvs_version does not match this VS Command Prompt or the
>    gyp ERR! find VS installation cannot be used.
>    gyp ERR! find VS
>    gyp ERR! find VS **************************************************************
>    gyp ERR! find VS You need to install the latest version of Visual Studio
>    gyp ERR! find VS including the "Desktop development with C++" workload.
>    gyp ERR! find VS For more information consult the documentation at:
>    gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
>    gyp ERR! find VS **************************************************************
>    gyp ERR! find VS
>    gyp ERR! configure error
>    gyp ERR! stack Error: Could not find any Visual Studio installation to use
>    gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
>    gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
>    gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:367:16
>    gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
>    gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
>    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
>    gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
>    gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
>    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
>    gyp ERR! System Windows_NT 6.1.7601
>    gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
>"rebuild"
>    gyp ERR! cwd D:\Home\icenter-next\node_modules\ref-napi
>    gyp ERR! node -v v12.8.1
>    gyp ERR! node-gyp -v v5.0.3
>    gyp ERR! not ok
>    error Command failed with exit code 1.
>
>                    command='C:\Program Files (x86)\nodejs\node.exe' 'C:\Program Files (x86)\Yarn\bin\yarn.js' run install
>                    workingDir=D:\Home\icenter-next\node_modules\ref-napi
>  ? D:\Home\icenter-next\node_modules\app-builder-bin\win\ia32\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
>                                                                                                                                       Error: D:\Home\icenter-ne
>xt\node_modules\app-builder-bin\win\ia32\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
>                                                                                                                                           at ChildProcess.<anon
>ymous> (D:\Home\icenter-next\node_modules\app-builder-lib\node_modules\builder-util\src\util.ts:239:14)
>                                                                                                                                           at Object.onceWrapper
> (events.js:291:20)
>                                                                                                                                           at ChildProcess.emit
>(events.js:203:13)
>                                                                                                                                           at maybeClose (intern
>al/child_process.js:1021:16)
>                                                                                                                                           at Process.ChildProce
>ss._handle.onexit (internal/child_process.js:283:5)
>error Command failed with exit code 1.
>info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
>
>D:\Home\icenter-next>npm config delete ELECTRON_MIRROR
>
>D:\Home\icenter-next>npm config list
>; cli configs
>metrics-registry = "https://registry.npmjs.org/"
>scope = ""
>user-agent = "npm/6.10.2 node/v12.8.1 win32 ia32"
>
>; userconfig C:\Users\10079130\.npmrc
>http-proxy = "http://proxyhk.zte.com.cn:80/"
>https-proxy = "http://proxyhk.zte.com.cn:80/"
>msvs_version = "2017"
>proxy = "http://proxyhk.zte.com.cn:80/"
>strict-ssl = false
>
>; builtin config undefined
>prefix = "C:\\Users\\10079130\\AppData\\Roaming\\npm"
>
>; node bin location = C:\Program Files (x86)\nodejs\node.exe
>; cwd = D:\Home\icenter-next
>; HOME = C:\Users\10079130
>; "npm config ls -l" to show all defaults.
>
>
>D:\Home\icenter-next>yarn install
>yarn install v1.22.0
>[1/4] Resolving packages...
>success Already up-to-date.
>$ electron-builder install-app-deps && node hooks/fix_electron_installation.js
>   electron-builder  version=22.3.2
>   rebuilding native dependencies  dependencies=ffi-napi@2.4.6, ref-napi@1.4.3 platform=win32 arch=ia32
>   rebuilding native dependency  name=ffi-napi version=2.4.6
>   rebuilding native dependency  name=ref-napi version=1.4.3
>Done in 40.67s.

</details>

**Comment by bzoz** [comment] 2020-03-10 15:29
Sorry, cannot reproduce.

Can you try updating Node to a newer version? Could you also provide a self-contained sample that reproduces this issue?

**Comment by bzoz** [comment] 2020-03-30 13:48
No follow-up, closing.

**Closed by bzoz** 2020-03-30 13:48 UTC
