### ISSUE TITLE
Not download electron from custom mirror

### ISSUE THREAD

**Issue by stefanJi** [nodejs/node-gyp#2676] opened 2022-06-02 07:01 UTC
* **Node Version**:  v14.19.2 6.14.17
* **Platform**:  macos 12.3.1
* **Compiler**:  unix
* **Module**:  ffi-napi@4.0.3

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
webpack 5.72.0 compiled successfully in 23227 ms
[1] npm run build-renderer exited with code 0
  • electron-builder  version=23.0.3 os=21.4.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=out/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, ref-napi@3.0.3 platform=darwin arch=x64
  ⨯ cannot execute  cause=exit status 1
                    out=
> ffi-napi@4.0.3 install /Users/X/Documents/repo/y-z-pc/node_modules/ffi-napi
> node-gyp-build
                    errorOut=gyp WARN install got an error, rolling back install
    gyp ERR! configure error
    gyp ERR! stack Error: 404 response downloading https://electronjs.org/headers/v15.3.3-tt.3.release.main.3/node-v15.3.3-tt.3.release.main.3.tar.gz
    gyp ERR! stack     at go (/Users/X/Documents/repo/y-z-pc/node_modules/node-gyp/lib/install.js:153:17)
    gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
    gyp ERR! stack     at async install (/Users/X/Documents/repo/y-z-pc/node_modules/node-gyp/lib/install.js:62:18)
    gyp ERR! System Darwin 21.4.0
    gyp ERR! command "/Users/X/Documents/repo/node-v14.19.2-darwin-x64/bin/node" "/Users/X/Documents/repo/y-z-pc/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/X/Documents/repo/y-z-pc/node_modules/ffi-napi
    gyp ERR! node -v v14.19.2
    gyp ERR! node-gyp -v v8.4.1
    gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! ffi-napi@4.0.3 install: `node-gyp-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the ffi-napi@4.0.3 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/X/.npm/_logs/2022-06-02T06_54_57_423Z-debug.log

                    command=/Users/X/Documents/repo/node-v14.19.2-darwin-x64/bin/node /Users/X/Documents/repo/node-v14.19.2-darwin-x64/lib/node_modules/npm/bin/npm-cli.js rebuild ffi-napi@4.0.3 ref-napi@3.0.3
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! y-z-pc@0.0.3 package-mac: `npm run build && electron-builder build --mac`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the y-z-pc@0.0.3 package-mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/X/.npm/_logs/2022-06-02T06_54_57_489Z-debug.log
```

</details>

electron-builder config:

```
"build": {
    "appId": "xxx",
    "files": [
      "dist/",
      "package.json",
    ],
    "asar": true,
    "asarUnpack": [
      "src/main/imcppsdk/lib/"
    ],
    "mac": {
      "category": "public.app-category.developer-tools",
      "target": "dmg",
      "hardenedRuntime": true,
      "type": "development"
    },
    "directories": {
      "output": "out"
    },
    "electronVersion": "15.3.3-tt.3.release.main.3",
    "electronDownload": {
      "mirror": "custom mirror"
    }
  }
```

**Comment by cclauss** [comment] 2022-06-02 10:37
@addaleax Any hints?

**Comment by addaleax** [comment] 2022-06-02 10:59
Don’t really have anything to do with this :)

**Comment by cclauss** [comment] 2022-06-02 11:05
[`npm ERR! ffi-napi@4.0.3 install: node-gyp-build`](https://www.npmjs.com/package/ffi-napi)

**Comment by cclauss** [comment] 2024-08-27 08:12
Duplicate of
* node-ffi-napi/node-ffi-napi#269

https://github.com/nodejs/node-gyp/labels/ffi-napi

**Closed by cclauss** 2024-08-27 08:12 UTC
Labels: macOS, ffi-napi
