### ISSUE TITLE
ELFIECYCLE Exit Status: 7 bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by Sheepsaurus** [nodejs/node-gyp#1710] opened 2019-04-04 11:48 UTC
* **Node Version**: node -v: v10.15.3 - node-gyp -v: v3.8.0
* **Module**: bluetooth-hci-socket

<details><summary>Verbose output (from npm or node-gyp):</summary>

PS C:\xampp\htdocs\minidronejs> npm install bluetooth-hci-socket

> usb@1.5.0 install C:\xampp\htdocs\minidronejs\node_modules\usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[usb] Success: "C:\xampp\htdocs\minidronejs\node_modules\usb\src\binding\usb_bindings.node" is installed via remote

> bluetooth-hci-socket@0.5.1 install C:\xampp\htdocs\minidronejs\node_modules\bluetooth-hci-socket
> node-gyp rebuild

C:\xampp\htdocs\minidronejs\node_modules\bluetooth-hci-socket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\minidronejs\node_modules\bluetooth-hci-socket
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bluetooth-hci-socket@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

</details>

**Comment by Mr1008** [comment] 2019-04-08 11:35
Another issue with VS 2019. Node-gyp does not support it for now :(
#1663

**Comment by bnoordhuis** [comment] 2019-05-06 07:51
Closing as a duplicate of #1663.

**Closed by bnoordhuis** 2019-05-06 07:51 UTC
