### ISSUE TITLE
Installing html2jade node module generates "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py:852: Warning: 'as' will become a reserved keyword in Python 2.6"

### ISSUE THREAD

**Issue by Abdelkrim** [nodejs/node-gyp#315] opened 2013-08-25 10:12 UTC
While installing https://github.com/donpark/html2jade using "sudo npm install -g html2jade", following gyp error occurs: 

`python --version` generates `Python 2.7.1`

Could you help me tackling the issue?

Thx in advance

```
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py:852: Warning: 'as' will become a reserved keyword in Python 2.6
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp", line 15, in <module>
    import gyp
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 852
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/html2jade/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
```

**Comment by gmcnaught** [comment] 2018-03-13 14:01
I cannot reproduce this in node 6.12.3 or 8.10.0. This should be closed.

**Comment by maclover7** [comment] 2018-07-20 18:33
Closing due to @gmcnaught's comment that this cannot be reproduced on version of Node.js that are still maintained.

**Closed by maclover7** 2018-07-20 18:33 UTC
