### ISSUE TITLE
node-gyp hard-codes --generator_output to 'build' in PWD directory

### ISSUE THREAD

**Issue by dnwe** [nodejs/node-gyp#486] opened 2014-08-06 10:18 UTC
Currently the output of node-gyp is hard-coded to be placed in $PWD/build (in configure.js `output_dir = path.resolve('build')` (for Windows) and just `output_dir = 'build'` for unix)

It would be useful if we could specify a custom output directory as a command-line option to node-gyp either via a node-gyp specific option `node-gyp configure --build_dir=/tmp/somedir` or by allowing us to pass-through our own generator_output parameter to pygyp: `node-gyp configure -- --generator_output=/tmp/somedir`

**Comment by kjwenger** [comment] 2015-12-23 12:15
+1

**Comment by phtaylor** [comment] 2016-12-14 15:22
+1!
Common guys, isn't this a pretty basic request for a build system? (its almost 2017)

**Comment by RebelSyntax** [comment] 2018-07-03 18:13
2018 checking in.  I need to move this location thanks to an issue when dealing with asar package structure.

**Comment by maclover7** [comment] 2018-07-31 19:05
Duplicate of #263, closing in favor of that issue (which has a WIP pull request attached to it)

**Closed by maclover7** 2018-07-31 19:05 UTC
