### ISSUE TITLE
node-gyp fails: /root/.node-gyp/5.0.0/common.gypi not found

### ISSUE THREAD

**Issue by yurivict** [nodejs/node-gyp#819] opened 2015-11-21 03:55 UTC
I first run 'npm install --ignore-scripts', then 'npm rebuild'. It fails to build sqlite3, but here people had the same problem with another project: https://botbot.me/freenode/webtorrent/2015-11-01/?tz=America/Los_Angeles

Here is log:
```
> sqlite3@3.1.1 install /usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp: /root/.node-gyp/5.0.0/common.gypi not found (cwd: /usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System FreeBSD 10.2-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3/lib/binding/node-v47-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3/lib/binding/node-v47-freebsd-x64" "--python=/usr/local/bin/python2"
gyp ERR! cwd /usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

**Comment by bnoordhuis** [comment] 2015-11-21 11:34
Does `/root/.node-gyp/5.0.0/` exist and if so, what's in it?

**Comment by yurivict** [comment] 2015-11-21 11:44
```
$ ls -l /root/.node-gyp/5.0.0
drwxr-xr-x  3 502   staff  512 Oct 26 16:00 include
-rw-r--r--  1 root  staff    2 Nov 21 03:42 installVersion
```

**Comment by bnoordhuis** [comment] 2015-11-21 11:55
Then I guess the problem is this:

> gyp ERR! node-gyp -v v1.0.3

Your copy of node-gyp is too old to know that it needs to look in the `include/` sub-directory.

**Comment by yurivict** [comment] 2015-11-21 12:22
But the failed command here is also node-pre-gyp. So I better report this to pre-gyp.

**Comment by bnoordhuis** [comment] 2015-11-21 12:28
Not a bad idea although I infer from the error message that node-pre-gyp took the `--fallback-to-build` path, where it invokes node-gyp.

**Comment by vot** [comment] 2016-04-15 13:25
I know it's probably no use to you by now but I had the same issue with a different module.
What worked for me was removing the .node-gyp folder (next time node-gyp is called it will rebuild it).

In your scenario that would be `rm -rf /root/.node-gyp`

**Comment by bnoordhuis** [comment] 2016-04-28 12:57
Closing, looks like it's resolved and possibly wasn't a node-gyp issue to begin with.

**Closed by bnoordhuis** 2016-04-28 12:57 UTC

**Comment by callafeucht** [comment] 2016-07-14 14:57
@bnoordhuis sorry to bring up an old issue, but my team is running into some trouble with inconsistent location of the common.gypi file as well. Could you clarify why this file gets placed differently by different versions of node-gyp, and could you suggest a minimum version of node-gyp to use to ensure it knows to look in the include folder?

**Comment by bnoordhuis** [comment] 2016-07-14 16:12
> Could you clarify why this file gets placed differently by different versions of node-gyp

@callafeucht node-gyp used to download the full node.js source tarball but that was streamlined to only download the necessary header files.

> could you suggest a minimum version of node-gyp to use to ensure it knows to look in the include folder?

Any version less than (approximately) a year old.  If you're going to upgrade, I'd just upgrade to the latest version, though.

**Comment by callafeucht** [comment] 2016-07-14 16:37
@bnoordhuis Thank you!! We are seeing this issue in Jenkins where we have some 10-15 different versions and combinations of Node, npm, and N|Solid installed in parallel, so there are separate node-gyp installations for all of them, some older, some newer. I'll work with my team to ensure we clean out the older versions that are installed.

**Comment by luiscarbonell** [comment] 2020-02-27 06:41
Hey guys working with `node-gyp -v v3.6.2` on `node -v v13.9.0` on Ubuntu 18.04...running into a similar issue :man_shrugging:

**stack trace**

```
gyp: /usr/include/nodejs/common.gypi not found
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-40-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/codemonk/Downloads/node-opengl
gyp ERR! node -v v13.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by cclauss** [comment] 2020-02-27 06:48
Please upgrade node-gyp https://github.com/nodejs/node-gyp/releases
