### ISSUE TITLE
msbuild.exe failed with exit code: 2148734720

### ISSUE THREAD

**Issue by RichardBollinger** [nodejs/node-gyp#978] opened 2016-07-04 21:58 UTC
I am using node-gyp to install node java. I fought through all kinds of SDK and .NET Framework issues. Now I get 0x80131700. First I installed node-gyp, but not globally because it gets put under AppData/Roaming or something like that. Later globally. At bottom is what I have loaded so far.

Thanks in advance for any help you can give me.

Rick

C:\Program Files (x86)\nodejs>npm install java
\

> java@0.7.2 install C:\Program Files (x86)\nodejs\node_modules\java
> node-gyp rebuild

C:\Program Files (x86)\nodejs\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\nod
e_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 2148734720
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.j
s:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files (x86)\nodejs\node_modules\java
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli
.js" "install" "java"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.7.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\nodejs\npm-debug.log

C:\Program Files (x86)\nodejs>npm ls
C:\Program Files (x86)\nodejs
└─┬ npm@2.15.8
  ├── abbrev@1.0.9
  ├── ansi@0.3.1
  ├── ansi-regex@2.0.0
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── archy@1.0.0
  ├── async-some@1.0.2
  ├── block-stream@0.0.9
  ├── char-spinner@1.0.1
  ├── chmodr@1.0.2
  ├── chownr@1.0.1
  ├── cmd-shim@2.0.2
  ├─┬ columnify@1.5.4
  │ └─┬ wcwidth@1.0.0
  │   └─┬ defaults@1.0.3
  │     └── clone@1.0.2
  ├─┬ config-chain@1.1.10
  │ └── proto-list@1.2.4
  ├─┬ dezalgo@1.0.3
  │ └── asap@2.0.3
  ├── editor@1.0.0
  ├── fs-vacuum@1.2.9
  ├─┬ fs-write-stream-atomic@1.0.8
  │ └── iferr@0.1.5
  ├── fstream@1.0.10
  ├─┬ fstream-npm@1.0.7
  │ └── fstream-ignore@1.0.3
  ├── github-url-from-git@1.4.0
  ├── github-url-from-username-repo@1.0.2
  ├─┬ glob@7.0.4
  │ ├── fs.realpath@1.0.0
  │ └── path-is-absolute@1.0.0
  ├── graceful-fs@4.1.4
  ├── hosted-git-info@2.1.4
  ├── imurmurhash@0.1.4
  ├── inflight@1.0.5
  ├── inherits@2.0.1
  ├── ini@1.3.4
  ├─┬ init-package-json@1.9.4
  │ ├─┬ glob@6.0.4
  │ │ └── path-is-absolute@1.0.0
  │ └── promzard@0.3.0
  ├── lockfile@1.0.1
  ├─┬ lru-cache@4.0.1
  │ ├── pseudomap@1.0.2
  │ └── yallist@2.0.0
  ├─┬ minimatch@3.0.0
  │ └─┬ brace-expansion@1.1.1
  │   ├── balanced-match@0.2.1
  │   └── concat-map@0.0.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ node-gyp@3.3.1
  │ ├─┬ glob@4.5.3
  │ │ └─┬ minimatch@2.0.10
  │ │   └─┬ brace-expansion@1.1.5
  │ │     ├── balanced-match@0.4.1
  │ │     └── concat-map@0.0.1
  │ ├─┬ minimatch@1.0.0
  │ │ ├── lru-cache@2.7.3
  │ │ └── sigmund@1.0.1
  │ └─┬ path-array@1.0.1
  │   └─┬ array-index@1.0.0
  │     ├─┬ debug@2.2.0
  │     │ └── ms@0.7.1
  │     └─┬ es6-symbol@3.1.0
  │       ├── d@0.1.1
  │       └─┬ es5-ext@0.10.12
  │         └── es6-iterator@2.0.0
  ├── nopt@3.0.6
  ├── normalize-git-url@3.0.2
  ├─┬ normalize-package-data@2.3.5
  │ └─┬ is-builtin-module@1.0.0
  │   └── builtin-modules@1.1.0
  ├── npm-cache-filename@1.0.2
  ├── npm-install-checks@1.0.7
  ├── npm-package-arg@4.1.0
  ├─┬ npm-registry-client@7.1.2
  │ ├─┬ concat-stream@1.5.1
  │ │ ├─┬ readable-stream@2.0.6
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── isarray@1.0.0
  │ │ │ ├── process-nextick-args@1.0.7
  │ │ │ ├── string_decoder@0.10.31
  │ │ │ └── util-deprecate@1.0.2
  │ │ └── typedarray@0.0.6
  │ └── retry@0.8.0
  ├── npm-user-validate@0.1.4
  ├─┬ npmlog@2.0.4
  │ ├─┬ are-we-there-yet@1.1.2
  │ │ └── delegates@1.0.0
  │ └─┬ gauge@1.2.7
  │   ├── has-unicode@2.0.0
  │   ├─┬ lodash.pad@4.4.0
  │   │ ├── lodash._baseslice@4.0.0
  │   │ ├── lodash._basetostring@4.12.0
  │   │ └── lodash.tostring@4.1.3
  │   ├─┬ lodash.padend@4.5.0
  │   │ ├── lodash._baseslice@4.0.0
  │   │ ├── lodash._basetostring@4.12.0
  │   │ └── lodash.tostring@4.1.3
  │   └─┬ lodash.padstart@4.5.0
  │     ├── lodash._baseslice@4.0.0
  │     ├── lodash._basetostring@4.12.0
  │     └── lodash.tostring@4.1.3
  ├── once@1.3.3
  ├── opener@1.4.1
  ├─┬ osenv@0.1.3
  │ ├── os-homedir@1.0.0
  │ └── os-tmpdir@1.0.1
  ├── path-is-inside@1.0.1
  ├─┬ read@1.0.7
  │ └── mute-stream@0.0.5
  ├─┬ read-installed@4.0.3
  │ ├── debuglog@1.0.1
  │ ├── readdir-scoped-modules@1.0.2
  │ └── util-extend@1.0.1
  ├─┬ read-package-json@2.0.4
  │ ├─┬ glob@6.0.4
  │ │ └── path-is-absolute@1.0.0
  │ └─┬ json-parse-helpfulerror@1.0.3
  │   └── jju@1.3.0
  ├─┬ readable-stream@2.1.4
  │ ├── buffer-shims@1.0.0
  │ ├── core-util-is@1.0.2
  │ ├── isarray@1.0.0
  │ ├── process-nextick-args@1.0.7
  │ ├── string_decoder@0.10.31
  │ └── util-deprecate@1.0.2
  ├── realize-package-specifier@3.0.1
  ├─┬ request@2.72.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.3.2
  │ ├─┬ bl@1.1.2
  │ │ └─┬ readable-stream@2.0.6
  │ │   ├── core-util-is@1.0.2
  │ │   ├── isarray@1.0.0
  │ │   ├── process-nextick-args@1.0.7
  │ │   ├── string_decoder@0.10.31
  │ │   └── util-deprecate@1.0.2
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@1.0.0-rc4
  │ │ └── async@1.5.2
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├── has-ansi@2.0.0
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.13.1
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@2.0.0
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.2.2
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.2
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.8.3
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── dashdash@1.13.1
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├── getpass@0.1.6
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.13.3
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.11
  │ │ └── mime-db@1.23.0
  │ ├── node-uuid@1.4.7
  │ ├── oauth-sign@0.8.2
  │ ├── qs@6.1.0
  │ ├── stringstream@0.0.5
  │ ├── tough-cookie@2.2.2
  │ └── tunnel-agent@0.4.3
  ├── retry@0.9.0
  ├─┬ rimraf@2.5.2
  │ └─┬ glob@7.0.0
  │   └── path-is-absolute@1.0.0
  ├── semver@5.1.0
  ├─┬ sha@2.0.1
  │ └─┬ readable-stream@2.0.2
  │   ├── core-util-is@1.0.1
  │   ├── isarray@0.0.1
  │   ├── process-nextick-args@1.0.3
  │   ├── string_decoder@0.10.31
  │   └── util-deprecate@1.0.1
  ├── slide@1.1.6
  ├── sorted-object@2.0.0
  ├── spdx-license-ids@1.2.1
  ├── strip-ansi@3.0.1
  ├── tar@2.2.1
  ├── text-table@0.2.0
  ├── uid-number@0.0.6
  ├── umask@1.1.0
  ├─┬ validate-npm-package-license@3.0.1
  │ ├── spdx-correct@1.0.2
  │ └─┬ spdx-expression-parse@1.0.2
  │   └── spdx-exceptions@1.0.4
  ├─┬ validate-npm-package-name@2.2.2
  │ └── builtins@0.0.7
  ├─┬ which@1.2.10
  │ └── isexe@1.1.2
  ├── wrappy@1.0.2
  └── write-file-atomic@1.1.4

**Comment by rvagg** [comment] 2016-07-05 05:19
@RichardBollinger sorry I can't help much more, the logs are so unhelpful in cases like this. Can I suggest you go clone the node-java repo and try rebuilding it from there. If you use `node-gyp` directly to do a `node-gyp rebuild` there's a chance you may get more helpful information .. a chance .. You may also need to set your `msvs_version` in npm (just guessing here tbh), see the README @ https://github.com/nodejs/node-gyp for information. If you're messaround with .NET stuff perhaps you have multiple versions of MSVS installed and it's getting mixed up.

**Comment by bnoordhuis** [comment] 2016-07-05 08:51
Exit code 2148734720 suggests either VS or .NET Framework is in a bad state.  I don't have anything more specific to offer but it probably means the issue is not with node-gyp or node-java.

**Comment by RichardBollinger** [comment] 2016-07-05 15:17
I really appreciate all the prompt comments with good ideas. 

I am not using the VS 2015 option. I am using Option 1 and installed VCBuild. It came in the c++ redistributables of the faulty 2010 vintage. I had to delete them to get around a MS bug in them that tainted the installs of .NET Framework 4 Extended and Client Profile, and Windows SDK for Windows 7 (7.1). So, the 2010 vintage files got reinstalled with the SDK. I think I have only the one unique configuration (state) that works for Windows 7.

I did 'npm config set msvs_version 2015'. It did not help. Same errors.
I did 'npm rebuild node-gyp'. There was no output, so I assume there were no errors.
I would have used node-gyp directly to do a node-gyp rebuild. But, I don't know how.
I am a newbie at all this. So, I don't think cloning the repo will help at this stage.

Thanks a bunch.
Rick

**Comment by RichardBollinger** [comment] 2016-07-05 17:58
Under Windows users not happy, I found this curious post. It says '-g on windows 7 is not correct.' But, that appears to be a requirement for node-gyp on windows.
============================
Updating npm's bundled node gyp
peter--bolier--zero edited this page 29 days ago · 8 revisions

npm bundles its own, internal, copy of node-gyp. This internal copy is independent of any globally installed copy of node-gyp that you may have installed via npm install -g node-gyp.

This means that while node-gyp doesn't get installed into your $PATH by default, npm still keeps its own copy to invoke when you attempt to npm install a native addon.

Sometimes, you may need to update npm's internal node-gyp to a newer version than what is installed. A simple npm install -g node-gyp won't do the trick since npm will still continue to use its internal copy over the global one.

So instead:
Linux, Mac OS X, Solaris, etc.

Unix is easy. Just run the following command. Use sudo if necessary.

$ [sudo] npm explore npm -g -- npm install node-gyp@latest

Windows

Windows is a bit tricker, since npm gets installed to the "Program Files" directory, which needs admin privileges in order to modify on current Windows. Therefore, run the following commands inside a cmd.exe started with "Run as Administrator":

First we need to find the location of node. If you don't already know the location that node.exe got installed to, then run:

$ npm install -g which
$ which node

As an alternative to the above, those on Windows Server 2003 and later (this includes Windows 7) can run:

$ where node

Now cd to the directory that node.exe is contained in, and with node_modules\npm at the end. i.e.:

$ cd "C:\Program Files\nodejs\node_modules\npm"

Now you can finally run:

$ npm install -g node-gyp@latest

note: i found that the -g on windows 7 is not correct. It gets installed in C:\Users<name>\AppData\Roaming\npm\node_modules\gyp which is not the directory where node is installed C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp...

**Comment by RichardBollinger** [comment] 2016-07-06 16:33
So, now I am at a build error (see below). I have given up on global installs until I can get a local install to work. I now have the NET Framework 4.5.1 that is needed. And, still the SDK 7.1. I fixed my registry so that Cpp files can be found. error C2373 seems to be internal problems and or version mismatches between products. So, I am stuck here for while. (See what happens when I try to update the version of node-gyp bundled with npm bundled with node.)

There has to be some magical combination of products and versions that will work.
Any help in the search would be appreciated.

Rick
========================================================error
C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge
_bindings.vcxproj]  
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotify  Hook2'
Done Building Project "C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge_bindings.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Program Files (x86)\nodejs\node_modules\java\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"C:\Program Files (x86)\nodejs\node_modules\java\build\binding.sln" (default target) (1) ->
"C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge_bindings.vcxproj" (default target) (2) ->
(ClCompile target) ->
  ..\src\utils.cpp(499): warning C4244: '=': conversion from 'jchar' to 'char', possible loss of data [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  ..\src\utils.cpp(616): warning C4244: '=': conversion from 'jchar' to 'char', possible loss of data [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\program files (x86)\nodejs\node_modules\nan\nan_new.h(214): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data (compiling source file ..\src\utils.cpp) [C:\Program Files (x86)\nodejs\node_modules\java\build
\nodejavabridge_bindings.vcxproj]


"C:\Program Files (x86)\nodejs\node_modules\java\build\binding.sln" (default target) (1) ->
"C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge_bindings.vcxproj" (default target) (2) ->
(ClCompile target) ->
  C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabrid
ge_bindings.vcxproj]

    3 Warning(s)
    1 Error(s)

Time Elapsed 00:00:15.13
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files (x86)\nodejs\node_modules\java
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm verb lifecycle java@0.7.2~install: unsafe-perm in lifecycle true
npm verb lifecycle java@0.7.2~install: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files (x86)\nodejs\node_modules\java\node_modules\.bin;C:\Program Files (x86)\nodejs\node_modules\.bin;C:\Program Files (x86)\
nodejs;C:\Program Files\Python27\;C:\Program Files\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windo
ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Progra
m Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Windows\SysWOW64\WindowsPowerShell\v1.0;C:\Program Files (x86)\MySQL\MySQL Server 5.5\bin;C:\Program Files (x86)\Common Files\In
tuit\QBPOSSDKRuntime;C:\Program Files (x86)\Acronis\TrueImageHome\;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Git\bin\;C:\Program Files\Microsoft SQL Se
rver\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\WindowsPerformance Toolkit\;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\GnuWin32;C:\Program Files (x86)\Java\jdk1.7.0\bi
n;C:\Program Files (x86)\CVSNT\;C:\Program Files (x86)\Java\jdk1.8.0_66\lib\jvm.lib;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\vcpackages;C:\Users\Rick\AppData\Roaming\npm;C:\Program Files (x86)\MSBuild\14.0\Bin\amd64
npm verb lifecycle java@0.7.2~install: CWD: C:\Program Files (x86)\nodejs\node_modules\java
npm info lifecycle java@0.7.2~install: Failed to exec install script
npm verb unlock done using C:\Users\Rick\AppData\Roaming\npm-cache\_locks\staging-64c461511ddedb71.lock for C:\Program Files (x86)\nodejs\node_modules\.staging
npm WARN enoent ENOENT: no such file or directory, open 'C:\Program Files (x86)\nodejs\package.json'
npm WARN nodejs No description
npm WARN nodejs No repository field.
npm WARN nodejs No README data
npm WARN nodejs No license field.
npm verb stack Error: java@0.7.2 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:852:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid java@0.7.2
npm verb cwd C:\Program Files (x86)\nodejs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "java" "--verbose" "--save"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! java@0.7.2 install: `node-gyp rebuild`

===========================================
C:\Program Files (x86)\nodejs\node_modules\npm>npm install node-gyp@3.4.0

concat-map@0.0.1 node_modules\node-gyp\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map -> node_modules\concat-map
d@0.1.1 node_modules\node-gyp\node_modules\path-array\node_modules\array-index\node_modules\es6-symbol\node_modules\d -> node_modules\d
es6-iterator@2.0.0 node_modules\node-gyp\node_modules\path-array\node_modules\array-index\node_modules\es6-symbol\node_modules\es5-ext\node_modules\es6-iterator -> node_modules\es6-iterator
ms@0.7.1 node_modules\node-gyp\node_modules\path-array\node_modules\array-index\node_modules\debug\node_modules\ms -> node_modules\ms
debug@2.2.0 node_modules\node-gyp\node_modules\path-array\node_modules\array-index\node_modules\debug -> node_modules\debug

array-index@1.0.0 node_modules\node-gyp\node_modules\path-array\node_modules\array-index -> node_modules\array-index
- balanced-match@0.3.0 node_modules\node-gyp\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match
- brace-expansion@1.1.3 node_modules\node-gyp\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion
- minimatch@2.0.10 node_modules\node-gyp\node_modules\glob\node_modules\minimatch
- glob@4.5.3 node_modules\node-gyp\node_modules\glob
- lru-cache@2.7.3 node_modules\node-gyp\node_modules\minimatch\node_modules\lru-cache
- sigmund@1.0.1 node_modules\node-gyp\node_modules\minimatch\node_modules\sigmund
- minimatch@1.0.0 node_modules\node-gyp\node_modules\minimatch
- es5-ext@0.10.11 node_modules\node-gyp\node_modules\path-array\node_modules\array-index\node_modules\es6-symbol\node_modules\es5-ext
- es6-symbol@3.0.2 node_modules\node-gyp\node_modules\path-array\node_modules\array-index\node_modules\es6-symbol
path-array@1.0.1 node_modules\node-gyp\node_modules\path-array -> node_modules\path-array
npm@3.9.5 C:\Program Files (x86)\nodejs\node_modules\npm
`-- node-gyp@3.4.0  invalid
  +-- minimatch@3.0.2
  | `-- brace-expansion@1.1.5
  |   `-- balanced-match@0.4.1
  `-- path-array@1.0.1
    `-- array-index@1.0.0
      `-- es6-symbol@3.1.0
        `-- es5-ext@0.10.12

**Comment by sethmurphy18** [comment] 2016-07-13 02:54
From what I am aware, based on some changes made to the source code of node-gyp about a month ago, and what I have read online this process should fix most if not all issues related to node-gyp on Windows.

* Open a Command Prompt as administrator
* `cd` to wherever you have Node installed, then `\node-modules\npm`
   - By default, this would be `C:\Program Files\nodejs\node-modules\npm`
* Run the following command `npm install node-gyp@latest`
* If you see node-gyp at the top of the tree with `INVALID` next to it, you did it right
* This is an issue with npm itself, not node-gyp

**Comment by joaocgreis** [comment] 2016-07-18 18:25
@sethmurphy18 that is true for very old versions of node. But for any recent version of node you should do `npm install -g npm@latest` and it will work (changing files in `Program Files` will create problems when uninstalling or updating).

@RichardBollinger that error about `__pfnDliNotifyHook2` is known and fixed in the last version of npm (both lts and master). Can you update with `npm install -g npm@latest`?

**Comment by sethmurphy18** [comment] 2016-07-18 22:33
@joaocgreis I was running Node 6.2.1 and had to do it. If you don't feel comfortable changing into the `Program Files` directory and doing it manually, Microsoft is even aware of the issue, and has released an NPM package to allow NPM to update itself. More on that [here](https://www.npmjs.com/package/npm-windows-upgrade).

**Closed** 2017-07-06 21:23 UTC
